[workspace]
members = ["primary", "node", "store", "crypto", "worker", "network", "config", "metrics"]
resolver = "2"

[workspace.dependencies]
tokio = "1"
tokio-util = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.7"
bincode = "1.3"
bytes = "1"
futures = "0.3"
async-trait = "0.1"
async-recursion = "0.3"
rand = "0.8"
anyhow = "1.0"
clap = { version = "4", features = ["cargo"] }
base64 = "0.22"
blake3 = "1.5"
rocksdb = { version = "0.23", features = ["lz4", "zstd"] }
serial_test = "0.9"
prometheus = "0.13"
axum = "0.7"
fdlimit = "0.3"
lz4_flex = "0.11"
