[package]
name = "store"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition = "2021"
publish = false

[dependencies]
rocksdb = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "rt", "time"] }
fdlimit = { workspace = true }
log = { workspace = true }
