[package]
name = "store"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
rocksdb = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "rt", "time"] }
fdlimit = { workspace = true }
log = { workspace = true }
