[package]
name = "primary"
version = "0.1.0"
authors = ["Libra <oncall+libra@xmail.facebook.com>"]
publish = false
edition = "2021"

[dependencies]
futures = { workspace = true }
serial_test = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt", "macros", "time"] }
tokio-util = { workspace = true, features = ["codec", "time"] }
blake3 = { workspace = true }
thiserror = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }

crypto = { path = "../crypto" }
store = { path = "../store" }
config = { path = "../config" }
network = { path = "../network" }
metrics = { path = "../metrics" }
prometheus = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[features]
benchmark = []
