// Simple-IT wiring layer: `SimpleItCore` drives `simpleit::engine::CutEngine` over the
// SAME data plane `vantage::node::VantageCore` uses (`LaneManager`/`Repairer`/`Wire`/
// `PayloadIo`, reused verbatim) -- own separate instances, deliberately not shared
// mutable state with any live Vantage assembly, since the two protocols are mutually
// exclusive per node/run (`config::Protocol` selects exactly one). Simple-IT has no
// separate `wire` submodule of its own the way Vantage does; this file is where its
// gate/dispatch/effect-execution logic lives instead, mirroring the combined role
// `vantage::node`+`vantage::wire` play for Vantage's own `Inbound`.
//
// Two oracles `CutEngine` needs from its caller (see engine.rs's own module doc
// comment) are supplied here: the per-round `Cut` snapshot (`SimpleItCore::build_cut`,
// from `LaneManager::c_candidate`) and the f+1 tip-availability gate
// (`TipOracleAdapter`, over `LaneManager::is_q_available`).

use crate::messages::{Ack, Header, Proposal};
use crate::primary::{Height, PrimaryMessage, CHANNEL_CAPACITY};
use crate::simpleit::effects::{CutEffect, CutOut};
use crate::simpleit::engine::{self, CutEngine, TipOracle};
use crate::simpleit::messages::{Cut, CutRound};
use crate::vantage::block;
use crate::vantage::lanes::{
    AckAggregator, AckAvailability, AvailEntry, BlockCache, LaneManager, SharedAckAggregator,
    SharedBlocks,
};
use crate::vantage::payload::PayloadIo;
use crate::vantage::repair::Repairer;
use crate::vantage::resume::{ResumeServe, ResumeTrigger};
use crate::vantage::wire::{self, DeclaredSender, Wire};
use crate::vantage::{BlockRef, Effect};
use async_trait::async_trait;
use bytes::Bytes;
use config::{Committee, Parameters, Protocol, WorkerId};
use crypto::{Digest, PublicKey};
use futures::stream::{FuturesUnordered, StreamExt};
use metrics::Metrics;
use network::{BatchConfig, MessageHandler, ReliableSender, SimpleSender, Writer};
use parking_lot::Mutex;
use std::collections::{BTreeMap, HashMap, HashSet, VecDeque};
use std::error::Error;
use std::future::Future;
use std::net::SocketAddr;
use std::pin::Pin;
use std::sync::Arc;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};
use store::Store;
use tokio::sync::mpsc::{channel, Receiver, Sender};

/// SECURITY (Fable audit): `simpleit::Inbound`'s half of the generic non-member gate
/// (`vantage::wire::sender_is_member`) -- see that function's doc comment for the full
/// rationale, and `vantage::wire`'s `impl DeclaredSender for vantage::node::Inbound` for
/// the sibling implementation this mirrors. Each cut-consensus message names its own
/// author/proposer directly (`CutProposal::proposer`; `CutVote`/`Decide`/`Timeout`/
/// `TimeoutAccept::author`). There is no longer a `CutCertificate`-shaped variant here
/// at all (removed -- see `engine.rs`'s module doc comment, "FIGURE-2 REWRITE"): that
/// type carried no single claimed sender (only an aggregate `votes: Vec<PublicKey>`
/// list any party could assemble and relay), and mapping it to `None` was exactly the
/// gate this whole security model could NOT close on its own -- membership-gating a
/// relayed aggregate says nothing about whether its claimed voters actually voted.
/// `TimerFired` is locally generated by this node's own armed timer, never received
/// over the wire, so it maps to `None`. `CutFetch` carries an explicit requester
/// (mirrors `vantage::node::Inbound::ControlFetch`), so it maps to `Some`. `CutServe`
/// carries a `CutProposal` whose `proposer` field names the ORIGINAL round leader, not
/// the relaying/serving party -- there is no sender claim on this variant to bind,
/// exactly like Vantage's own `ControlServe`, so it maps to `None` too (gated
/// downstream instead, by `CutEngine::on_cut_serve`'s own `pending_cut_fetch` check).
/// `CutReady` (BRACHA VARIANT ADDITION) carries a real, per-destination-verifiable
/// `author` field, same class as `CutVote`/`Decide`/`Timeout`/`TimeoutAccept` above.
impl DeclaredSender for engine::Inbound {
    fn declared_sender(&self) -> Option<PublicKey> {
        match self {
            engine::Inbound::CutProposal(p) => Some(p.proposer),
            engine::Inbound::CutVote(v) => Some(v.author),
            engine::Inbound::CutReady(r) => Some(r.author),
            engine::Inbound::Decide(d) => Some(d.author),
            engine::Inbound::Timeout(t) => Some(t.author),
            engine::Inbound::TimeoutAccept(a) => Some(a.author),
            engine::Inbound::TimerFired(_) => None,
            engine::Inbound::CutFetch(_, _, requester) => Some(*requester),
            engine::Inbound::CutServe(_) => None,
        }
    }
}

/// Inbound messages routed to `SimpleItCore`, either from the network
/// (`SimpleItReceiverHandler`) or -- for the wire-shared data-plane variants -- the
/// exact same message shapes `vantage::node::Inbound` carries. Deliberately NOT
/// `engine::Inbound` itself: that type is `CutEngine`'s own, cut-consensus-only
/// message set (it has no way to carry a `Header`/ack/repair message at all); this
/// wraps it in one variant (`Cut`) alongside the data-plane ones, mirroring how
/// `vantage::node::Inbound` unifies Vantage's own data-plane and AGB-consensus
/// messages into one channel type. `TimerFired` is deliberately never wrapped here --
/// see `SimpleItCore::run`'s own timer branch, which calls `CutEngine::handle`
/// directly instead of routing a locally-generated event through this wire-oriented
/// type (mirroring `VantageCore::run`'s identical treatment of its own AGB/
/// control-round timers).
#[derive(Debug, Clone)]
pub enum Inbound {
    /// `Header(h, false)`: publish path. Provenance is claimed-by-author, exactly as
    /// `vantage::node::Inbound::Publish` -- there is no channel identity to compare
    /// `h.author` against, so the dispatcher always passes `h.author` itself as the
    /// trusted sender.
    Publish(PublicKey, Header),
    /// `Header(h, true)`: serve path.
    Serve(Header),
    HeadersRequest(Vec<Digest>, PublicKey),
    /// Production network ACKs are accumulated by `AckAggregator` before reaching the
    /// core -- see `SimpleItReceiverHandler::dispatch`.
    AckAvailability(AckAvailability),
    /// Optional ack-watermark front-end (`Parameters::ack_watermarks`), mirroring
    /// `vantage::node::Inbound::Avail` exactly -- see `LaneManager::resolve_watermark`.
    Avail(Vec<AvailEntry>, PublicKey),
    /// The five wire-received cut-consensus messages, forwarded to `CutEngine::handle`
    /// verbatim.
    Cut(engine::Inbound),
    /// Mechanism A (sender-side lane resume, `vantage::resume`): a peer's
    /// `VantageLaneResume(author, from, requester)` -- mirrors `vantage::node::
    /// Inbound::LaneResume` exactly (same wire message, same data plane).
    LaneResume(PublicKey, Height, PublicKey),
}

impl DeclaredSender for Inbound {
    fn declared_sender(&self) -> Option<PublicKey> {
        match self {
            Inbound::Publish(sender, _) => Some(*sender),
            Inbound::HeadersRequest(_, requestor) => Some(*requestor),
            Inbound::Serve(_) | Inbound::AckAvailability(_) => None,
            Inbound::Avail(_, s) => Some(*s),
            Inbound::Cut(cut_inbound) => cut_inbound.declared_sender(),
            // Mechanism A: mirrors `vantage::node::Inbound`'s own identical arm.
            Inbound::LaneResume(_, _, requester) => Some(*requester),
        }
    }
}

/// Network receiver handler for the Simple-IT assembly's `primary_to_primary` port.
/// Deliberately a distinct type from `VantageReceiverHandler` (which stays untouched)
/// -- the two assemblies never share a handler -- but mirrors it closely: same
/// ack-aggregator behaviour, same frame acking (moved into `network::Receiver` itself,
/// once per received frame -- see `VantageReceiverHandler`'s own doc comment for why).
#[derive(Clone)]
pub struct SimpleItReceiverHandler {
    pub tx: Sender<Inbound>,
    pub ack_aggregator: SharedAckAggregator,
    /// `None` only in tests that construct this handler directly without wiring
    /// metrics; production (`Primary::spawn`) always passes `Some`.
    pub metrics: Option<Arc<Metrics>>,
}

#[async_trait]
impl MessageHandler for SimpleItReceiverHandler {
    async fn dispatch(
        &self,
        _writer: &mut Writer,
        serialized: Bytes,
    ) -> Result<(), Box<dyn Error>> {
        let message: PrimaryMessage = bincode::deserialize(&serialized)?;

        if let Some(metrics) = &self.metrics {
            crate::primary::record_typed_received(metrics, message.type_name(), serialized.len());
        }

        let inbound = match message {
            PrimaryMessage::Header(h, false) => Inbound::Publish(h.author, h),
            PrimaryMessage::Header(h, true) => Inbound::Serve(h),
            PrimaryMessage::HeadersRequest(digests, requestor) => {
                Inbound::HeadersRequest(digests, requestor)
            }
            PrimaryMessage::VantageAck(a) => {
                let result = {
                    let mut aggregator = self.ack_aggregator.lock();
                    aggregator.record_ack(a.sender, a.reference())
                };
                if !result.accepted {
                    if let Some(metrics) = &self.metrics {
                        metrics.vantage_rejected_nonmember_total.inc();
                    }
                    return Ok(());
                }
                if let Some(metrics) = &self.metrics {
                    metrics.vantage_acks_received.inc();
                }
                let Some(availability) = result.availability else {
                    return Ok(());
                };
                Inbound::AckAvailability(availability)
            }
            PrimaryMessage::VantageAvail(entries, sender) => Inbound::Avail(entries, sender),
            PrimaryMessage::SimpleItCutProposal(p) => Inbound::Cut(engine::Inbound::CutProposal(p)),
            PrimaryMessage::SimpleItCutVote(v) => Inbound::Cut(engine::Inbound::CutVote(v)),
            PrimaryMessage::SimpleItDecide(d) => Inbound::Cut(engine::Inbound::Decide(d)),
            PrimaryMessage::SimpleItTimeout(t) => Inbound::Cut(engine::Inbound::Timeout(t)),
            PrimaryMessage::SimpleItTimeoutAccept(a) => {
                Inbound::Cut(engine::Inbound::TimeoutAccept(a))
            }
            // BRACHA VARIANT ADDITION.
            PrimaryMessage::SimpleItCutReady(r) => Inbound::Cut(engine::Inbound::CutReady(r)),
            PrimaryMessage::SimpleItCutFetch(round, digest, requester) => {
                Inbound::Cut(engine::Inbound::CutFetch(round, digest, requester))
            }
            PrimaryMessage::SimpleItCutServe(p) => Inbound::Cut(engine::Inbound::CutServe(p)),
            // Mechanism A (`vantage::resume`).
            PrimaryMessage::VantageLaneResume(author, from, requester) => {
                Inbound::LaneResume(author, from, requester)
            }
            // Autobahn-only and Vantage-AGB-only variants never reach the Simple-IT
            // assembly's port; ignore rather than panic (defense in depth against a
            // misrouted message).
            _ => return Ok(()),
        };
        self.tx
            .send(inbound)
            .await
            .expect("Failed to send simpleit message");
        Ok(())
    }
}

/// The f+1 tip-availability oracle `CutEngine::handle` needs (deviation 3 in
/// engine.rs), over `LaneManager::is_q_available`. A small adapter borrowing
/// `&LaneManager`/`&Committee` directly, rather than `impl TipOracle for
/// SimpleItCore` -- `SimpleItCore`'s own dispatch needs `&mut self.cut` (for
/// `CutEngine::handle`'s receiver) live AT THE SAME TIME as the oracle argument, and
/// `impl TipOracle for SimpleItCore` would tie the oracle's borrow to `&self` as a
/// whole (conflicting with that `&mut self.cut`); borrowing only the two disjoint
/// fields it actually needs, via direct field-projection at each construction site,
/// avoids that conflict entirely (the same reason `VantageCore`'s own dispatch always
/// threads `&mut self.lm`/`&mut self.rep` as explicit arguments rather than calling
/// back through `self`).
struct TipOracleAdapter<'a> {
    lm: &'a LaneManager,
    committee: &'a Committee,
}

impl TipOracle for TipOracleAdapter<'_> {
    fn available_at_validity(&self, author: &PublicKey, tip: &Proposal) -> bool {
        let r: BlockRef = (*author, tip.height, tip.header_digest.clone());
        self.lm
            .is_q_available(&r, self.committee.validity_threshold())
    }
}

/// Every in-flight `CutEffect::ArmTimer` deadline, as a boxed future resolving to the
/// round it was armed for once its deadline elapses -- fed back as
/// `engine::Inbound::TimerFired(round)` by `SimpleItCore::run`'s own select branch.
/// `CutEngine::process_cut_timer` already no-ops a stale/redundant firing (round no
/// longer current, already certified, or already timed out -- see its own doc
/// comment), so this queue needs no cancellation/dedup of its own: every armed timer
/// simply fires once, for whatever `TimerFired` is worth by the time it does.
type PendingTimers = FuturesUnordered<Pin<Box<dyn Future<Output = CutRound> + Send>>>;

/// `try_expand_commit`'s success payload: the same `(by_worker, headers)` shape
/// `PayloadIo::notify_committed` takes, factored into a name (clippy::type_complexity)
/// rather than repeated inline.
type CommitBatch = (Vec<(WorkerId, Vec<Digest>)>, Vec<Header>);

/// The Simple-IT cut-consensus wiring task: owns its OWN instances of the same
/// data-plane types Vantage uses (`lm`, `ack_aggregator`, `rep`, `wire`, `payload`) --
/// deliberately separate state, not shared mutable state, since the two protocols are
/// mutually exclusive per node/run (identical data-plane logic either way, because it
/// is the same code, not merely the same configuration). Drives `cut: CutEngine`
/// (Simple-IT's own state machine) over that data plane, supplying both oracles its
/// `handle` method needs (`build_cut`, `TipOracleAdapter`).
pub struct SimpleItCore {
    name: PublicKey,
    /// SECURITY (Fable audit): mirrors `VantageCore::members` exactly -- the trusted
    /// committee-membership set `dispatch_inbound`'s gate checks every wire-declared
    /// sender against before any census/count path (here: `CutVoteAggregator`,
    /// `TimeoutAggregator`, `TimeoutAcceptAggregator`, `DecideAggregator`) ever sees
    /// the message.
    members: HashSet<PublicKey>,
    /// Needed at this layer (unlike `VantageCore`, which never keeps a raw copy) --
    /// `CutEngine::handle` takes `tips`/`oracle` as EXTERNAL parameters the caller
    /// computes fresh each call (see engine.rs's own module doc comment on why), so
    /// `build_cut`/`TipOracleAdapter` need direct committee access this level down.
    committee: Committee,
    lm: LaneManager,
    ack_aggregator: SharedAckAggregator,
    rep: Repairer,
    /// Reused verbatim from Vantage (`vantage::wire::Wire`) -- own instance, own
    /// network senders/cancel-handler bookkeeping.
    wire: Wire,
    /// Reused verbatim from Vantage (`vantage::payload::PayloadIo`) -- own instance,
    /// own D1 payload-sync bookkeeping and committed-output channel.
    payload: PayloadIo,
    cut: CutEngine,
    pending_timers: PendingTimers,

    header_size: usize,
    max_header_delay: u64,
    digests: Vec<(Digest, WorkerId)>,
    payload_size: usize,

    /// `Parameters::ack_watermarks` -- mirrors `vantage::node::VantageCore`'s
    /// identical field exactly: when `true`, the N3 per-block ack broadcast is
    /// suppressed at EXECUTION time (`execute`'s `Effect::BroadcastAck` arm), while
    /// the local self-ack path (`record_local_ack`) still runs unconditionally either
    /// way. `LaneManager` itself never sees this flag.
    ack_watermarks: bool,
    /// The ack-watermark broadcast period, ms -- irrelevant when `ack_watermarks` is
    /// off.
    ack_watermark_period_ms: u64,

    /// Mechanism A (sender-side lane resume, `vantage::resume`) -- mirrors
    /// `vantage::node::VantageCore`'s identical fields exactly (own separate
    /// instances, same reasoning as every other data-plane field on this struct).
    /// Unconditional protocol behavior (no flag) -- every party always runs this
    /// check.
    resume_trigger: ResumeTrigger,
    resume_serve: ResumeServe,
    /// `Parameters::resume_check_period_ms` -- the `run` loop's `resume_tick` period.
    resume_check_period_ms: u64,
    /// `Parameters::resume_backoff_ms` -- shared by both `resume_trigger` and
    /// `resume_serve`.
    resume_backoff_ms: u64,
    /// `Parameters::resume_batch` -- the maximum own blocks served per resume batch.
    resume_batch: u64,

    /// Session id / genesis digest, computed once at `build` time (mirrors
    /// `VantageCore::build`'s identical locals) -- kept as fields because
    /// `try_expand_commit` needs `genesis` for a not-yet-committed author's default
    /// watermark, and both are required (if unused) positional arguments to
    /// `BlockCache::collect_verified_suffix`.
    sid: Digest,
    genesis: Digest,
    max_block_payload: usize,
    /// Simple-IT's own minimal analogue of `vantage::Cursor`'s per-author
    /// `watermarks` field -- see `try_expand_commit`'s doc comment for why a full
    /// `Cursor` isn't reused. Absent entry means "nothing committed yet for this
    /// author" (implicitly `(0, genesis)`). Only ever advanced once EVERY author in
    /// a round has been proven locally resolvable -- see `drain_commit_queue`.
    committed_watermark: HashMap<PublicKey, (Height, Digest)>,
    /// Committed-but-not-yet-fully-materialised rounds, in ascending round order
    /// (`BTreeMap`, not `HashMap` -- standing project rule: prunable/ordered
    /// structures are keyed for `split_off`/order, never scanned). A round can sit
    /// here for a while under normal operation, not just under a fault: this node can
    /// commit a round via reaching `safe` (its own `mint_threshold`-many first-hand
    /// votes) plus a quorum of `Decide`s without ever having voted on (or gated via
    /// `gate_tips`/gate on) that round's own tips --
    /// `LaneManager::is_q_available` means 2f+1 PEERS acked a tip, not that THIS node
    /// holds its bytes. See `drain_commit_queue`'s doc comment for the resulting
    /// safety requirement (materialise strictly in round order, all authors of a
    /// round atomically, or not at all).
    commit_queue: BTreeMap<CutRound, Cut>,
    /// Simple-IT's own retention window (`Parameters::simpleit_gc_window_rounds`,
    /// clamped to >= 1 by `build` -- see that field's doc comment), in cut ROUNDS,
    /// mirroring `VantageCore::gc_window`'s role for Vantage's own views.
    gc_window: CutRound,
    /// The floor `CutEngine::prune_below` was last called with (0 if never) --
    /// mirrors `VantageCore::last_gc_floor`'s identical monotonic-guard role.
    last_gc_floor: CutRound,

    metrics: Option<Arc<Metrics>>,
}

/// `SimpleItCore::build`'s return shape -- mirrors `VantageCore::build`'s
/// `BuildOutput` exactly.
type BuildOutput = (
    SimpleItCore,
    Receiver<Inbound>,
    Receiver<(Digest, Digest, WorkerId)>,
    Sender<Inbound>,
    SharedAckAggregator,
);

impl SimpleItCore {
    // clippy::too_many_arguments: see primary/src/committer.rs's identical
    // justification (mirrors `VantageCore::spawn`'s own identical annotation).
    #[allow(clippy::too_many_arguments)]
    pub fn spawn(
        name: PublicKey,
        committee: Committee,
        parameters: Parameters,
        store: Store,
        metrics: Option<Arc<Metrics>>,
        rx_our_digests: Receiver<(Digest, WorkerId)>,
        tx_output: Sender<Header>,
    ) -> (Sender<Inbound>, SharedAckAggregator) {
        let (core, rx_simpleit, rx_payload_ready, tx_simpleit, ack_aggregator) =
            Self::build(name, committee, parameters, store, metrics, tx_output);
        tokio::spawn(core.run(rx_simpleit, rx_our_digests, rx_payload_ready));
        (tx_simpleit, ack_aggregator)
    }

    #[allow(clippy::too_many_arguments)]
    fn build(
        name: PublicKey,
        committee: Committee,
        parameters: Parameters,
        store: Store,
        metrics: Option<Arc<Metrics>>,
        tx_output: Sender<Header>,
    ) -> BuildOutput {
        let (tx_simpleit, rx_simpleit) = channel(CHANNEL_CAPACITY);
        let (tx_payload_ready, rx_payload_ready) = channel(CHANNEL_CAPACITY);

        // SECURITY (Fable audit): captured before `committee` is consumed below
        // building the sub-components -- see `VantageCore::build`'s identical
        // comment.
        let members: HashSet<PublicKey> = committee.authorities.keys().cloned().collect();

        let sid = block::session_id(&committee);
        let genesis = block::genesis_digest(&sid);
        let blocks: SharedBlocks = Arc::new(Mutex::new(BlockCache::new()));
        let ack_aggregator: SharedAckAggregator =
            Arc::new(Mutex::new(AckAggregator::new(committee.clone())));

        let mut lm = LaneManager::with_shared_blocks(
            name,
            committee.clone(),
            parameters.max_block_payload,
            store.clone(),
            blocks.clone(),
        );
        let mut rep = Repairer::new(
            name,
            committee.clone(),
            sid.clone(),
            genesis.clone(),
            parameters.max_block_payload,
            blocks,
        );
        let core_metrics = metrics.clone();
        if let Some(m) = metrics {
            lm = lm.with_metrics(m.clone());
            rep = rep.with_metrics(m);
        }

        // Paper-faithful defaults: `gate_tips: true`, no crash-injection scaffolding.
        // Neither is exposed via `Parameters` -- not asked for, and inventing a CLI
        // knob for either is out of scope here. `variant` IS exposed, indirectly,
        // through `parameters.protocol`: `Protocol::SimpleItBracha` selects
        // `engine::Variant::Bracha`, every other `Protocol` value selects
        // `engine::Variant::Opt` (the only one of the five `SimpleItCore::build` is
        // ever ACTUALLY reached under in practice -- `primary.rs`'s own
        // `Protocol::SimpleIt | Protocol::SimpleItBracha` match arm is this
        // function's only caller; the other three arms are covered here anyway,
        // matching this crate's own no-wildcard-match convention rather than relying
        // on that external invariant).
        let variant = match parameters.protocol {
            Protocol::SimpleItBracha => engine::Variant::Bracha,
            Protocol::SimpleIt
            | Protocol::AutobahnOptimistic
            | Protocol::AutobahnSeamless
            | Protocol::Vantage => engine::Variant::Opt,
        };
        let cut =
            CutEngine::new(name, committee.clone(), parameters.timeout_delay).with_variant(variant);

        let other_primaries: Vec<(PublicKey, SocketAddr)> = committee
            .others_primaries(&name)
            .into_iter()
            .map(|(pk, addr)| (pk, addr.primary_to_primary))
            .collect();
        let other_primary_addrs: Vec<SocketAddr> =
            other_primaries.iter().map(|(_, a)| *a).collect();

        // Data-plane withholding fault injector (`--withhold`): mirrors
        // `VantageCore::build`'s identical resolve-once-here treatment (same shared
        // `Wire`, same field) -- see `Wire::withheld_header_dests`'s own doc comment.
        let withheld_header_dests: wire::WithheldHeaderDests =
            config::withheld_destinations(&committee, &name, parameters.withhold_senders).map(
                |blocked| {
                    let full: Vec<(PublicKey, SocketAddr)> = other_primaries
                        .iter()
                        .filter(|(pk, _)| !blocked.contains(pk))
                        .copied()
                        .collect();
                    let addrs: Vec<SocketAddr> = full.iter().map(|(_, a)| *a).collect();
                    (addrs, full)
                },
            );

        let worker_addresses: HashMap<WorkerId, SocketAddr> = committee
            .our_workers_by_id(&name)
            .expect("Our public key is not in the committee")
            .into_iter()
            .map(|(id, addr)| (id, addr.primary_to_worker))
            .collect();

        let latency_map = parameters
            .latency_table
            .as_deref()
            .map(|table| committee.latency_map(&name, table))
            .unwrap_or_default();

        let batch = BatchConfig {
            enabled: parameters.batch_messages,
            max_bytes: parameters.batch_max_bytes,
            max_delay_ms: parameters.batch_max_delay_ms,
        };

        // Mechanism A (sender-side lane resume, `vantage::resume`): this node's own
        // dedicated off-run-loop sender -- mirrors `VantageCore::build`'s identical
        // construction exactly (see `wire::spawn_resume_sender`'s doc comment for
        // the full design/rationale). Built from the SAME `latency_map`/`batch`/
        // `core_metrics` locals as `network`/`worker_network` just below -- cloned
        // here (rather than moved) since both of those still need their own copies
        // afterward.
        //
        // reconnect-replay plan §7 (mechanical adaptation ONLY -- SimpleIt never
        // constructs `Effect::Broadcast*`'s outbox-recorded path, never opens a
        // replay episode, and never attaches `with_reconnect_events`/`with_drop_map`
        // to `network` below -- "no volatile, no events, no episodes"): `in_flight`
        // is a freshly constructed, permanently-unfed map (nothing here ever
        // inserts into it, since `Wire::enqueue_replay` is never called on this
        // assembly) and the chunk-pacing parameters are inert for the same reason --
        // still threaded through because `spawn_resume_sender`/`Wire` are the SAME
        // shared types Vantage uses.
        let in_flight: wire::InFlightMap = Arc::new(Mutex::new(HashMap::new()));
        let resume_senders = wire::spawn_resume_sender(
            latency_map.clone(),
            batch,
            core_metrics.clone(),
            in_flight.clone(),
            parameters.replay_chunk_bytes,
            parameters.replay_chunk_interval_ms,
            parameters.replay_serve_max_bytes,
            // KNOB 2 (measurement ablation, `config::Parameters::
            // retry_backoff_max_ms`): transport-level, applies to Simple-IT's
            // resume-sender pool too -- see `spawn_resume_sender`'s own doc
            // comment.
            parameters.retry_backoff_max_ms,
        );

        let core = Self {
            name,
            members,
            committee,
            lm,
            ack_aggregator: ack_aggregator.clone(),
            rep,
            wire: Wire {
                network: {
                    let mut s = ReliableSender::new()
                        .with_latency(latency_map.clone())
                        .with_batching(batch)
                        // KNOB 2 (measurement ablation, `config::Parameters::
                        // retry_backoff_max_ms`): transport-level, applies to
                        // Simple-IT's main pool too -- see that field's own doc
                        // comment. Unlike Vantage, Simple-IT never attaches
                        // `with_reconnect_events`/`with_drop_map` here at all
                        // (KNOB 1's reconnect-replay mechanism is Vantage-only --
                        // see the comment above `resume_senders`' own construction),
                        // so this is the only new knob this pool needs.
                        .with_retry_backoff_max_ms(parameters.retry_backoff_max_ms);
                    if let Some(m) = &core_metrics {
                        s = s.with_metrics(m.clone());
                    }
                    s
                },
                worker_network: {
                    let mut s = SimpleSender::new()
                        .with_latency(latency_map)
                        .with_batching(batch);
                    if let Some(m) = &core_metrics {
                        s = s.with_metrics(m.clone());
                    }
                    s
                },
                resume_lane_tx: resume_senders.lane,
                replay_tx: resume_senders.replay,
                replay_generation: resume_senders.generation,
                cancel_handlers: Vec::new(),
                last_prune_len: 0,
                other_primaries: other_primaries.clone(),
                other_primary_addrs,
                worker_addresses,
                withheld_header_dests,
                withhold_window: parameters.withhold_window.clone(),
                metrics: core_metrics.clone(),
                addr_to_peer: other_primaries
                    .iter()
                    .map(|(pk, addr)| (*addr, *pk))
                    .collect(),
                dirty_map: Arc::new(Mutex::new(HashMap::new())),
                in_flight,
            },
            payload: PayloadIo {
                pending_payload: HashMap::new(),
                store,
                tx_payload_ready,
                tx_output,
            },
            cut,
            pending_timers: FuturesUnordered::new(),
            header_size: parameters.header_size,
            max_header_delay: parameters.max_header_delay,
            digests: Vec::new(),
            payload_size: 0,
            ack_watermarks: parameters.ack_watermarks,
            ack_watermark_period_ms: parameters.ack_watermark_period_ms,
            resume_trigger: ResumeTrigger::new(),
            resume_serve: ResumeServe::new(),
            resume_check_period_ms: parameters.resume_check_period_ms,
            resume_backoff_ms: parameters.resume_backoff_ms,
            resume_batch: parameters.resume_batch,
            sid,
            genesis,
            max_block_payload: parameters.max_block_payload,
            committed_watermark: HashMap::new(),
            commit_queue: BTreeMap::new(),
            // Clamped to >= 1: a window of 0 would put the GC floor at the current
            // round itself and prune state for the round being resolved -- mirrors
            // `VantageCore::build`'s identical clamp on `vantage_gc_window_views`.
            gc_window: parameters.simpleit_gc_window_rounds.max(1),
            last_gc_floor: 1,
            metrics: core_metrics,
        };
        (
            core,
            rx_simpleit,
            rx_payload_ready,
            tx_simpleit,
            ack_aggregator,
        )
    }

    async fn run(
        mut self,
        mut rx_simpleit: Receiver<Inbound>,
        mut rx_our_digests: Receiver<(Digest, WorkerId)>,
        mut rx_payload_ready: Receiver<(Digest, Digest, WorkerId)>,
    ) {
        // Boot: the round-1 leader proposes, and every party (leader included, in
        // case IT then stalls after its own proposal) arms round 1's own fallback
        // timeout -- see `CutEngine::schedule_cut_timer`'s doc comment for why round 1
        // is the one round no other engine method ever arms a timer for (every other
        // round's timer is armed as a side effect of the engine advancing INTO it,
        // which by definition cannot happen for the first round).
        let effects = {
            let tips = self.build_cut();
            let oracle = TipOracleAdapter {
                lm: &self.lm,
                committee: &self.committee,
            };
            let mut effects = self.cut.try_propose_cut_for_current_round(&tips, &oracle);
            effects.extend(self.cut.schedule_cut_timer(1));
            effects
        };
        self.execute_cut(effects).await;

        let header_timer = tokio::time::sleep(Duration::from_millis(self.max_header_delay));
        tokio::pin!(header_timer);

        // Fable perf audit item 4's own mechanism (`Wire::prune_cancel_handlers`),
        // reused verbatim here -- see `VantageCore::run`'s identical `metrics_tick`
        // branch (minus the Vantage-specific progress-gauge sampling, which has no
        // Simple-IT analogue).
        let mut prune_tick = tokio::time::interval(Duration::from_secs(1));
        prune_tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);

        // Optional ack-watermark front-end (`Parameters::ack_watermarks`): mirrors
        // `VantageCore::run`'s identical construction -- constructed ONLY when the
        // flag is on, so no tick is ever scheduled when it's off.
        let mut avail_tick = if self.ack_watermarks {
            let mut interval =
                tokio::time::interval(Duration::from_millis(self.ack_watermark_period_ms));
            interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
            Some(interval)
        } else {
            None
        };

        // Mechanism A (sender-side lane resume, `vantage::resume`): mirrors
        // `VantageCore::run`'s identical construction -- unconditional (no flag),
        // its own dedicated tick so `Parameters::resume_check_period_ms` is
        // genuinely honored.
        let mut resume_tick =
            tokio::time::interval(Duration::from_millis(self.resume_check_period_ms));
        resume_tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);

        loop {
            self.wire.maybe_prune_cancel_handlers();

            tokio::select! {
                biased;

                Some(inbound) = rx_simpleit.recv() => {
                    self.dispatch_inbound(inbound).await;
                }

                Some((header_digest, digest, worker_id)) = rx_payload_ready.recv() => {
                    self.on_payload_ready(header_digest, digest, worker_id).await;
                }

                Some((digest, worker_id)) = rx_our_digests.recv() => {
                    self.payload_size += digest.size();
                    self.digests.push((digest, worker_id));
                    if self.payload_size >= self.header_size {
                        self.seal_own_header().await;
                        header_timer.as_mut().reset(tokio::time::Instant::now() + Duration::from_millis(self.max_header_delay));
                    }
                }

                () = &mut header_timer => {
                    self.seal_own_header().await;
                    header_timer.as_mut().reset(tokio::time::Instant::now() + Duration::from_millis(self.max_header_delay));
                }

                // Guarded exactly like `VantageCore::run`'s own `agb_sleep`/
                // `control_sleep` branches (`if next_deadline.is_some()`): polling an
                // EMPTY `FuturesUnordered` resolves `Ready(None)` immediately rather
                // than pending, which would otherwise busy-loop this branch whenever
                // no timer is currently armed.
                Some(round) = self.pending_timers.next(), if !self.pending_timers.is_empty() => {
                    let effects = {
                        let tips = self.build_cut();
                        let oracle = TipOracleAdapter { lm: &self.lm, committee: &self.committee };
                        self.cut.handle(engine::Inbound::TimerFired(round), &tips, &oracle)
                    };
                    self.execute_cut(effects).await;
                }

                () = async {
                    match avail_tick.as_mut() {
                        Some(t) => { t.tick().await; }
                        None => std::future::pending::<()>().await,
                    }
                }, if avail_tick.is_some() => {
                    if let Some(entries) = self.lm.take_avail_flush() {
                        if let Some(metrics) = &self.metrics {
                            metrics.vantage_avail_sent.inc();
                        }
                        self.wire
                            .broadcast_message(PrimaryMessage::VantageAvail(entries, self.name))
                            .await;
                    }
                }

                // Mechanism A (design doc step 2): mirrors `VantageCore::run`'s
                // identical `resume_tick` branch -- the EPISODE DETECTOR/retry
                // driver; ongoing drain of an established episode instead runs at
                // receipt pace via `try_resume_request`'s other call sites
                // (`Inbound::Publish`/`on_payload_ready` in `dispatch_inbound`/
                // `on_payload_ready` below).
                _ = resume_tick.tick() => {
                    let now = Instant::now();
                    let authors: Vec<PublicKey> =
                        self.wire.other_primaries.iter().map(|(pk, _)| *pk).collect();
                    for author in authors {
                        self.try_resume_request(author, now);
                    }
                }

                _ = prune_tick.tick() => {
                    self.wire.prune_cancel_handlers();
                    self.collect_internal_garbage();
                }
            }
        }
    }

    /// The cut snapshot `CutEngine::handle` needs (oracle 1, engine.rs's own module
    /// doc comment): one entry per committee member with a certified tip
    /// (`LaneManager::c_candidate`, which itself requires `DirectPub` + 2f+1 acks --
    /// strictly stronger than upstream's certified-tips rule, intentionally).
    fn build_cut(&self) -> Cut {
        self.committee
            .authorities
            .keys()
            .filter_map(|author| {
                self.lm.c_candidate(author).map(|(_, height, digest)| {
                    (
                        *author,
                        Proposal {
                            header_digest: digest,
                            height,
                        },
                    )
                })
            })
            .collect()
    }

    /// SECURITY (Fable audit): mirrors `VantageCore::dispatch_inbound`'s centralized
    /// membership gate exactly, over the generic `sender_is_member`/`DeclaredSender`
    /// gate Phase 2 introduced. `Inbound::Cut(engine::Inbound::TimerFired(_))` never
    /// reaches this function (see `run`'s own timer branch, which calls
    /// `CutEngine::handle` directly), so the gate here only ever sees wire-originated
    /// input.
    async fn dispatch_inbound(&mut self, inbound: Inbound) {
        if !wire::sender_is_member(&inbound, &self.members) {
            if let Some(metrics) = &self.metrics {
                metrics.vantage_rejected_nonmember_total.inc();
            }
            return;
        }
        match inbound {
            Inbound::Publish(sender, header) => {
                // Mechanism A receipt-continuation (design doc step 3, mirrors
                // `VantageCore::dispatch_inbound`'s identical hook): this publish
                // may have just advanced `frontier(author)`.
                let author = header.author;
                let before = self.lm.own_direct_frontier(&author);
                let effects = self.lm.process_publish(sender, header).await;
                self.execute(effects).await;
                if self.lm.own_direct_frontier(&author) > before {
                    self.try_resume_request(author, Instant::now());
                }
            }
            Inbound::Serve(header) => {
                let effects = self.serve_effects(header).await;
                self.execute(effects).await;
            }
            Inbound::HeadersRequest(digests, requestor) => {
                let mut effects = Vec::new();
                for d in digests {
                    effects.extend(self.rep.on_request(requestor, d));
                }
                self.execute(effects).await;
            }
            Inbound::AckAvailability(availability) => {
                let effects = self.on_ack_availability(availability);
                self.execute(effects).await;
            }
            Inbound::Avail(entries, sender) => {
                if let Some(metrics) = &self.metrics {
                    metrics.vantage_avail_received.inc();
                }
                let refs = self.lm.resolve_watermark(sender, &entries);
                let effects = self.credit_refs(sender, refs);
                self.execute(effects).await;
            }
            Inbound::Cut(cut_inbound) => {
                let effects = {
                    let tips = self.build_cut();
                    let oracle = TipOracleAdapter {
                        lm: &self.lm,
                        committee: &self.committee,
                    };
                    self.cut.handle(cut_inbound, &tips, &oracle)
                };
                self.execute_cut(effects).await;
            }
            // Mechanism A (`vantage::resume`): mirrors `vantage::node::VantageCore::
            // dispatch_inbound`'s own `Inbound::LaneResume` arm exactly (same clamp,
            // dedup, and batch-cap decisions -- see that arm's own comments).
            Inbound::LaneResume(author, from, requester) => {
                if author != self.name {
                    return;
                }
                let floor = self.lm.earliest_authored_height(&author);
                let from = from.max(floor);
                let tip = self.lm.own_tip_height();
                if from > tip {
                    return;
                }
                let now = Instant::now();
                let backoff = Duration::from_millis(self.resume_backoff_ms);
                if !self
                    .resume_serve
                    .should_serve(requester, from, now, backoff)
                {
                    return;
                }
                let to = (from + self.resume_batch - 1).min(tip);
                let mut effects = Vec::with_capacity((to - from + 1) as usize);
                for height in from..=to {
                    if let Some(header) = self.lm.author_block_at(&author, height) {
                        if let Some(metrics) = &self.metrics {
                            metrics.vantage_lane_resume_blocks_served.inc();
                        }
                        effects.push(Effect::ResumeServeTo(requester, header));
                    }
                }
                self.execute(effects).await;
            }
        }
    }

    async fn serve_effects(&mut self, header: Header) -> Vec<Effect> {
        let digest = header.id.clone();
        let author = header.author;
        let mut effects = self.rep.on_serve(header.clone());
        let accepted = effects
            .iter()
            .any(|effect| matches!(effect, Effect::BlockCached(d) if *d == digest));
        if accepted {
            let missing = self.lm.missing_payload(&header).await;
            if !missing.is_empty() {
                effects.push(Effect::SyncBatches(author, digest, missing));
            }
        }
        effects
    }

    fn on_ack_availability(&mut self, availability: AckAvailability) -> Vec<Effect> {
        self.lm.process_ack_availability(availability)
    }

    fn record_local_ack(&mut self, ack: &Ack) -> Vec<Effect> {
        let availability = {
            let mut aggregator = self.ack_aggregator.lock();
            aggregator
                .record_ack(self.name, ack.reference())
                .availability
        };
        availability
            .map(|availability| self.on_ack_availability(availability))
            .unwrap_or_default()
    }

    /// Feeds `refs` (from `LaneManager::resolve_watermark`/`retry_pending_avail`)
    /// through the SAME shared `AckAggregator` the per-block ack path uses, and the
    /// SAME `on_ack_availability` path -- mirrors `vantage::node::VantageCore::
    /// credit_refs` exactly (this is the load-bearing property of the whole design:
    /// the watermark front-end and the per-block-ack front-end are indistinguishable
    /// below the aggregator). `sender` is already known to be a committee member
    /// (`dispatch_inbound`'s centralized gate ran before `Inbound::Avail` is ever
    /// reached).
    fn credit_refs(&mut self, sender: PublicKey, refs: Vec<BlockRef>) -> Vec<Effect> {
        let mut effects = Vec::new();
        for r in refs {
            let result = {
                let mut aggregator = self.ack_aggregator.lock();
                aggregator.record_ack(sender, r)
            };
            if !result.accepted {
                if let Some(metrics) = &self.metrics {
                    metrics.vantage_rejected_nonmember_total.inc();
                }
                continue;
            }
            if let Some(metrics) = &self.metrics {
                metrics.vantage_avail_credited_refs.inc();
            }
            if let Some(availability) = result.availability {
                effects.extend(self.on_ack_availability(availability));
            }
        }
        effects
    }

    /// Drains `initial` (and every effect transitively produced while draining it)
    /// against real I/O -- mirrors `VantageCore::execute`'s identical `VecDeque`-based
    /// loop, restricted to the six `Effect` variants `lm`/`rep` can actually produce.
    ///
    /// The remaining 26 `Effect` variants (every AGB/pacemaker/control-log/anchor/
    /// cursor-output variant `LaneManager`/`Repairer` never construct -- confirmed by
    /// inspection of both types' source: their only `Effect::` construction sites are
    /// `BroadcastPublish`, `BroadcastAck`, `SyncBatches`, `RequestTo`, `ServeTo`,
    /// `BlockCached`) are matched explicitly below rather than caught by a silent `_`
    /// or `unreachable!()`: they are genuinely unproducible on this path, but a panic
    /// in a validator is worse than an observable drop, so a debug build gets a loud
    /// `debug_assert!` while a release build just counts and drops.
    ///
    /// `Effect::ResumeServeTo` (Mechanism A, `vantage::resume`) is NOT in that list
    /// below, unlike every other AGB-family variant: it IS genuinely producible on
    /// this path, constructed directly by `dispatch_inbound`'s own `Inbound::
    /// LaneResume` arm (not by `lm`/`rep`), so it gets a real arm just below.
    /// `Effect::BroadcastSkipVote` joins this list -- `AgbEngine::
    /// recheck_skip_vote_trigger`'s only caller-visible effect, equally unproducible
    /// on this data-plane-only path.
    /// `Effect::BodyFetchTo`/`Effect::BodyServeTo` (signature-free.tex §8.3
    /// "Digest-named AGB statements") join the list too -- `vantage::agb::
    /// DigestStatements`'s own two caller-visible effects, equally unproducible here
    /// (Simple-IT has no AGB engine, and `Parameters::digest_statements` is
    /// Vantage-only).
    async fn execute(&mut self, initial: Vec<Effect>) {
        let mut queue: VecDeque<Effect> = initial.into();
        while let Some(effect) = queue.pop_front() {
            match effect {
                Effect::BroadcastPublish(header) => {
                    self.wire
                        .broadcast_message(PrimaryMessage::Header(header, false))
                        .await
                }
                Effect::BroadcastAck(ack) => {
                    // Self-ack path always runs; only the wire broadcast is
                    // suppressed when the watermark front-end replaces it -- mirrors
                    // `vantage::node::VantageCore::execute`'s identical gating.
                    queue.extend(self.record_local_ack(&ack));
                    if !self.ack_watermarks {
                        self.wire
                            .broadcast_message(PrimaryMessage::VantageAck(ack))
                            .await
                    }
                }
                Effect::SyncBatches(author, header_digest, missing) => {
                    self.payload
                        .sync_batches(&mut self.wire, author, header_digest, missing)
                        .await;
                }
                Effect::RequestTo(peer, digest) => {
                    self.wire
                        .send_message(
                            peer,
                            PrimaryMessage::HeadersRequest(vec![digest], self.name),
                        )
                        .await;
                }
                Effect::ServeTo(peer, header) => {
                    self.wire
                        .send_message(peer, PrimaryMessage::Header(header, true))
                        .await
                }
                Effect::BlockCached(digest) => {
                    // Ack-watermark front-end: retry any watermark pending on this
                    // author before `on_block_available` consumes `digest` by value.
                    // Extends the SAME queue this loop is draining (not a recursive
                    // `self.execute` call -- this arm already runs inside `execute`'s
                    // own drain loop).
                    for (sender, r) in self.lm.retry_pending_avail(&digest) {
                        queue.extend(self.credit_refs(sender, vec![r]));
                    }
                    queue.extend(self.rep.on_block_available(digest));
                    // Re-attempt the commit-materialisation queue: a newly-cached
                    // block (direct publish or repaired serve) is exactly the event
                    // that can newly satisfy `drain_commit_queue`'s per-author suffix
                    // check for whichever round is currently stuck at its head.
                    self.drain_commit_queue().await;
                    // NOTE (a separate, benign liveness question, unrelated to the
                    // commit path above): Simple-IT's own f+1 tip-availability gate
                    // (`gate_tips` in `process_cut_proposal`) is evaluated fresh from
                    // `LaneManager`'s CURRENT state on every `CutEngine::handle` call
                    // (`build_cut`/`TipOracleAdapter`), not cached -- but a VOTE that
                    // failed that gate on first arrival is not automatically
                    // re-driven when the missing tip later becomes available (the
                    // engine's own doc comment on `process_cut_proposal` says exactly
                    // this: it "does not itself invent such a retry"). Unlike the
                    // commit path, this is not a safety concern: a certificate/decide
                    // quorum formed by OTHER parties still lets this node commit (see
                    // `drain_commit_queue`'s doc comment), and this node's own missed
                    // vote is covered by the round's timeout ladder. Deliberately not
                    // addressed here since no retry mechanism was specified and
                    // `CutEngine` exposes none for this specific case (unlike
                    // `retry_pending_cut_proposals`, which the engine already invokes
                    // internally for the unrelated SAFE-PARENT-blocked case).
                }

                // --- Mechanism A (sender-side lane resume, `vantage::resume`) ---
                Effect::ResumeServeTo(requester, header) => {
                    // Non-blocking hand-off onto the dedicated resume-sender task
                    // (`Wire::enqueue_resume_header` -> `enqueue_resume`) -- never
                    // `.await`ed, so this costs the effect-drain loop nothing
                    // beyond the enqueue itself.
                    self.wire.enqueue_resume_header(requester, header);
                }
                other @ (Effect::BroadcastPropose(_)
                | Effect::BroadcastEcho(_)
                | Effect::BroadcastEchoSkip(_)
                | Effect::BroadcastReady(_)
                | Effect::BroadcastNoReady(_)
                | Effect::BroadcastSkipVote(_)
                | Effect::Fixed(_, _)
                | Effect::Completed(_, _, _)
                | Effect::Sealed(_, _)
                | Effect::ArmTimer(_, _, _)
                | Effect::NotifyCommitted(_, _, _)
                | Effect::BroadcastWish(_)
                | Effect::Enter(_)
                | Effect::RaiseWish(_)
                | Effect::CompletionReportable(_, _)
                | Effect::BroadcastCompReport(_, _)
                | Effect::BroadcastControlInit(_, _)
                | Effect::BroadcastControlEcho(_)
                | Effect::BroadcastControlReady(_)
                | Effect::BroadcastControlCommit(_)
                | Effect::BroadcastControlTimeoutVote(_)
                | Effect::BroadcastControlTimeoutAccept(_)
                | Effect::ControlFetchTo(_, _, _)
                | Effect::ControlServeTo(_, _, _)
                | Effect::ArmControlTimer(_, _)
                | Effect::ApplyAnchor(_, _, _)
                | Effect::BodyFetchTo(_, _, _)
                | Effect::BodyServeTo(_, _, _)) => {
                    debug_assert!(
                        false,
                        "SimpleItCore's data-plane effect loop received a Vantage-\
                         consensus-only Effect variant that lm/rep can never \
                         construct: {:?}",
                        other
                    );
                    if let Some(metrics) = &self.metrics {
                        metrics.simpleit_unexpected_effect_total.inc();
                    }
                }
            }
        }
    }

    /// `CutEffect`s never chain back into more `CutEffect`s (unlike `Effect` above) --
    /// none of the three variants' handling ever asks `cut` for further effects, so a
    /// plain `for` loop suffices; no `VecDeque` needed.
    async fn execute_cut(&mut self, effects: Vec<CutEffect>) {
        for effect in effects {
            match effect {
                CutEffect::Broadcast(out) => {
                    let message = match out {
                        CutOut::CutProposal(p) => PrimaryMessage::SimpleItCutProposal(p),
                        CutOut::CutVote(v) => PrimaryMessage::SimpleItCutVote(v),
                        CutOut::Decide(d) => PrimaryMessage::SimpleItDecide(d),
                        CutOut::Timeout(t) => PrimaryMessage::SimpleItTimeout(t),
                        CutOut::TimeoutAccept(a) => PrimaryMessage::SimpleItTimeoutAccept(a),
                        // BRACHA VARIANT ADDITION.
                        CutOut::CutReady(r) => PrimaryMessage::SimpleItCutReady(r),
                    };
                    self.wire.broadcast_message(message).await;
                }
                CutEffect::ArmTimer { round, deadline } => {
                    let deadline = tokio::time::Instant::from_std(deadline);
                    let fut: Pin<Box<dyn Future<Output = CutRound> + Send>> =
                        Box::pin(async move {
                            tokio::time::sleep_until(deadline).await;
                            round
                        });
                    self.pending_timers.push(fut);
                }
                CutEffect::Commit { round, proposals } => {
                    // Queue rather than emit directly -- see `drain_commit_queue`'s
                    // doc comment for why this cut's blocks may not be locally
                    // materialised yet, and why draining must stay round-ordered.
                    self.commit_queue.insert(round, proposals);
                    self.drain_commit_queue().await;
                }
                CutEffect::FetchTo {
                    peer,
                    round,
                    cut_id,
                } => {
                    self.wire
                        .send_message(
                            peer,
                            PrimaryMessage::SimpleItCutFetch(round, cut_id, self.name),
                        )
                        .await;
                }
                CutEffect::ServeTo { peer, proposal } => {
                    self.wire
                        .send_message(peer, PrimaryMessage::SimpleItCutServe(proposal))
                        .await;
                }
            }
        }
    }

    /// Drains `commit_queue` strictly in ascending round order. SAFETY (audit fix):
    /// a round is emitted only when EVERY one of its authors' suffixes resolves --
    /// atomically, all together -- and rounds are never reordered or skipped. Both
    /// are required, not stylistic:
    ///
    /// A correct node can reach `CutEffect::Commit` for a round whose blocks it does
    /// NOT hold: `try_commit_round`/`emit_commit_to_committer` fire once this node's
    /// own `safe`-marking (first-hand `mint_threshold` votes) lines up with a quorum
    /// of `Decide`s, none of which requires this node to have voted on (hence
    /// `gate_tips`-gated on) that round's own tips, and
    /// `record_cut_proposal` (which is what makes the cut's coordinates locally
    /// knowable at all) runs unconditionally on receipt, before any tip-availability
    /// check. So `try_expand_commit` returning `None` here is the COMMON case for a
    /// node whose repair walk hasn't caught up for some author's lane, not a
    /// corner case -- `LaneManager::is_q_available` (which is as far as `gate_tips`
    /// itself ever checks) means 2f+1 PEERS acked a tip, never that THIS node holds
    /// it.
    ///
    /// Given that, silently skipping an unresolved author (the previous version of
    /// this code) is a safety bug: it advances that round's OTHER authors into the
    /// output while leaving the unresolved author to be folded into whatever LATER
    /// round first resolves it, alongside that later round's own authors. Two nodes
    /// that resolve authors in a different order then interleave the SAME set of
    /// blocks differently across rounds -- same eventual set, different total order,
    /// which is exactly what a total-order broadcast must not do. Blocking the whole
    /// round (and everything queued after it) until it resolves atomically is the
    /// fix: every node emits the identical round-by-round, author-BTreeMap-order
    /// sequence, differing only in WHEN (never in WHAT order).
    async fn drain_commit_queue(&mut self) {
        while let Some(&round) = self.commit_queue.keys().next() {
            // Cloned out before calling `try_expand_commit` (which needs `&mut
            // self`) -- `Cut` is small (bounded by committee size) and this is not a
            // hot path (one commit's worth of coordinates per round, not per message).
            let proposals = self.commit_queue[&round].clone();
            let Some((by_worker, headers)) = self.try_expand_commit(&proposals) else {
                break;
            };
            self.commit_queue.remove(&round);
            let commit_millis = now_millis();
            self.payload
                .notify_committed(&mut self.wire, commit_millis, by_worker, headers)
                .await;
        }
        if let Some(metrics) = &self.metrics {
            metrics
                .simpleit_commit_queue_len
                .set(self.commit_queue.len() as i64);
        }
    }

    /// Simple-IT's own minimal analogue of `vantage::Cursor::expand`. `vantage::Cursor`
    /// itself isn't reused here: its `on_completed`/`on_sealed`/`pump` machinery
    /// exists to linearize AGB's ASYNCHRONOUS, out-of-order, View-keyed multi-input
    /// completion model (a view can be `Completed` and `Sealed` in either order,
    /// arbitrarily far apart) -- Simple-IT's `CutEffect::Commit` stream has no such
    /// complexity of its OWN (`CutEngine`'s own `sent_commit_rounds` latch already
    /// guarantees at most one `Commit` per round), so pulling in that whole state
    /// machine would be a worse fit than this direct port of just the piece Simple-IT
    /// actually needs. `Cursor` DOES also block until a manifest entry's chain is
    /// locally materialised (`expand` returns `None` and the caller waits for a
    /// `BlockCached` retry) -- that part IS needed here too, which is exactly
    /// `drain_commit_queue`'s job one level up; this function is the single-round,
    /// single-pass piece it calls.
    ///
    /// `proposals` (`CutEffect::Commit`'s cut) is a SNAPSHOT of per-author tips, not a
    /// delta since the last commit -- reporting it naively (just the tip block, on
    /// every round that still names it) would either silently drop every non-tip
    /// ancestor block committed since the last round, or re-report a tip's batches on
    /// every subsequent round that still names it (double-counting the worker-side
    /// commit-latency metric). This expands each author's NEW suffix since its own
    /// per-author watermark (mirroring `Cursor::expand`'s identical use of
    /// `BlockCache::collect_verified_suffix`), skipping authors with nothing new.
    ///
    /// Two-pass, all-or-nothing: pass 1 resolves (read-only) every author's suffix,
    /// bailing out via `?` -- mutating NOTHING -- the moment any one of them isn't
    /// yet locally available; only once every author has resolved does pass 2 apply
    /// the collected headers/batches and advance `committed_watermark`. This is what
    /// lets `drain_commit_queue` above emit a round atomically or not at all, never
    /// partially.
    fn try_expand_commit(&mut self, proposals: &Cut) -> Option<CommitBatch> {
        let blocks = self.lm.blocks_handle();
        let blocks = blocks.lock();

        // Pass 1: resolve, but do not yet apply, every author's suffix.
        let mut resolved: Vec<(PublicKey, Height, Digest, Vec<Digest>)> =
            Vec::with_capacity(proposals.len());
        for (author, proposal) in proposals {
            let (stop_height, stop_digest) = self
                .committed_watermark
                .get(author)
                .cloned()
                .unwrap_or_else(|| (0, self.genesis.clone()));
            if proposal.height <= stop_height {
                continue; // nothing new for this author -- vacuously resolved
            }
            // NOT a defensive/unreachable case: see `drain_commit_queue`'s doc
            // comment for why a correct node routinely reaches a commit for a round
            // whose blocks it hasn't yet locally verified all the way from its own
            // watermark. `?` here aborts pass 1 with `None`, before pass 2 has
            // mutated anything -- `drain_commit_queue` leaves this (and every later
            // queued) round in place and retries on the next `BlockCached`/
            // payload-ready trigger.
            let suffix = blocks.collect_verified_suffix(
                &self.committee,
                &self.sid,
                self.max_block_payload,
                stop_height,
                &stop_digest,
                &proposal.header_digest,
            )?;
            resolved.push((
                *author,
                proposal.height,
                proposal.header_digest.clone(),
                suffix,
            ));
        }

        // Pass 2: every author resolved -- apply.
        let mut by_worker: HashMap<WorkerId, Vec<Digest>> = HashMap::new();
        let mut headers = Vec::new();
        for (author, height, tip_digest, suffix) in resolved {
            for digest in &suffix {
                if let Some(entry) = blocks.get(digest) {
                    for (batch_digest, worker_id) in &entry.block.payload {
                        by_worker
                            .entry(*worker_id)
                            .or_default()
                            .push(batch_digest.clone());
                    }
                    headers.push(entry.block.clone());
                }
            }
            // `collect_verified_suffix` always pushes the walk's own starting digest
            // (`tip_digest`, i.e. `proposal.header_digest`) first and reverses at the
            // end, so `suffix.last()` (post-reverse) is provably `tip_digest` itself
            // whenever `suffix` is non-empty -- which pass 1's `proposal.height >
            // stop_height` guard guarantees (at least one step is taken before the
            // walk can hit its own stop condition). `tip_digest` is used directly
            // rather than re-deriving it from `suffix.last()`, so there is no
            // `Option`/index to ever panic on here.
            self.committed_watermark
                .insert(author, (height, tip_digest));
        }
        Some((by_worker.into_iter().collect(), headers))
    }

    /// Simple-IT's own analogue of `VantageCore::collect_internal_garbage`: prunes
    /// `CutEngine`'s per-round state once it has advanced far enough past the
    /// window's own floor. Unlike Vantage's resolver-driven floor, Simple-IT's
    /// progress indicator is just `CutEngine::cut_round` itself -- there is no
    /// separate resolved-watermark concept here. Deliberately independent of
    /// `commit_queue`: a round sitting in `commit_queue` waiting on repair has
    /// already had its `Cut` copied out (see `drain_commit_queue`'s doc comment), so
    /// pruning `CutEngine`'s OWN internal per-round maps below the floor cannot
    /// disturb it.
    fn collect_internal_garbage(&mut self) {
        let floor = self.cut.cut_round().saturating_sub(self.gc_window);
        if floor <= self.last_gc_floor {
            return;
        }
        self.cut.prune_below(floor);
        self.last_gc_floor = floor;
    }

    /// Seals whatever's accumulated in `self.digests` into our own header via
    /// `LaneManager::publish_own` -- mirrors `VantageCore::seal_own_header` exactly.
    async fn seal_own_header(&mut self) {
        let payload = self.digests.drain(..).collect();
        self.payload_size = 0;
        let (_, effects) = self.lm.publish_own(payload).await;
        self.execute(effects).await;
    }

    /// D1 payload-sync bookkeeping -- mirrors `VantageCore::on_payload_ready` exactly,
    /// including its Mechanism A receipt-continuation hook.
    async fn on_payload_ready(
        &mut self,
        header_digest: Digest,
        digest: Digest,
        worker_id: WorkerId,
    ) {
        let mut resolved = false;
        if let Some(set) = self.payload.pending_payload.get_mut(&header_digest) {
            set.remove(&(digest, worker_id));
            resolved = set.is_empty();
        }
        if resolved {
            self.payload.pending_payload.remove(&header_digest);
            // Mechanism A receipt-continuation (design doc step 3, mirrors
            // `VantageCore::on_payload_ready`'s identical hook): the DELAYED half
            // of "a resume-served header advances frontier(author)" -- taken
            // BEFORE `set_payload_ready`, which is the call that may actually
            // advance `own_direct_frontier` for it.
            let author = self.lm.author_of(&header_digest);
            let before = author.map(|a| self.lm.own_direct_frontier(&a));
            let effects = self.lm.set_payload_ready(&header_digest);
            self.execute(effects).await;
            // Defensive trigger, mirroring `Effect::BlockCached`'s identical one:
            // payload readiness does not currently change `collect_verified_suffix`'s
            // own answer (that depends only on `block_ok_verified`, set the moment a
            // header's CHAIN validity is confirmed, independent of its payload), but
            // re-attempting here costs little and keeps this call site aligned with
            // the other trigger point in case that independence ever changes.
            self.drain_commit_queue().await;
            if let (Some(author), Some(before)) = (author, before) {
                if self.lm.own_direct_frontier(&author) > before {
                    self.try_resume_request(author, Instant::now());
                }
            }
        }
    }

    /// Mechanism A (sender-side lane resume, `vantage::resume`) -- mirrors
    /// `VantageCore::try_resume_request` exactly, including its non-`async`
    /// signature (see that function's own doc comment for why: once the send
    /// itself became a non-blocking `try_send`, nothing in this body ever
    /// awaits). Shared by the periodic `resume_tick` and both receipt-continuation
    /// call sites (`dispatch_inbound`'s `Inbound::Publish` arm, `on_payload_ready`
    /// above).
    fn try_resume_request(&mut self, author: PublicKey, now: Instant) {
        let frontier = self.lm.own_direct_frontier(&author);
        let avail = self.lm.avail_high(&author);
        let backoff = Duration::from_millis(self.resume_backoff_ms);
        if let Some(from) =
            self.resume_trigger
                .check(author, frontier, avail, now, backoff, self.resume_batch)
        {
            if let Some(metrics) = &self.metrics {
                metrics.vantage_lane_resume_requests_sent.inc();
            }
            self.wire.enqueue_resume(
                author,
                PrimaryMessage::VantageLaneResume(author, from, self.name),
            );
        }
    }
}

/// `vantage::Cursor`'s own identical private helper, duplicated here rather than
/// exposed from `cursor.rs` for one non-test call site -- a one-line, dependency-free
/// wall-clock read.
fn now_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("time went backwards")
        .as_millis() as u64
}

#[cfg(test)]
mod tests {
    // Coverage for the commit-queue audit fix: `try_expand_commit`/`drain_commit_queue`
    // must materialise committed rounds strictly in ascending order, atomically (every
    // author of a round together or not at all), regardless of the order in which this
    // node's own repair walk happens to resolve each author's blocks -- see
    // `drain_commit_queue`'s own doc comment for the safety argument.
    use super::*;
    use crypto::Hash as _;

    fn key(byte: u8) -> PublicKey {
        PublicKey([byte; 32])
    }

    /// `n` committee members, `key(1)..=key(n)` -- mirrors
    /// `simpleit::engine::tests::committee_of`.
    fn committee_of(n: u8) -> Committee {
        let keys: Vec<PublicKey> = (1..=n).map(key).collect();
        let info = keys
            .iter()
            .enumerate()
            .map(|(i, k)| {
                (
                    *k,
                    1u32,
                    format!("127.0.0.1:{}", 9800 + i as u16).parse().unwrap(),
                )
            })
            .collect();
        Committee::new(info)
    }

    /// A real `SimpleItCore`, built through the same `build` path `spawn` uses (only
    /// skipping the final `tokio::spawn(core.run(..))`), mirroring `vantage::node::
    /// tests::test_core`'s identical pattern. Returns `rx_output` too -- the channel
    /// `PayloadIo::notify_committed` forwards each committed `Header` to, and the
    /// observation point these tests use instead of a live worker/network listener
    /// (this test committee's `Authority::workers` maps are empty, so `notify_committed`
    /// harmlessly finds no worker address to also notify -- see that function's own
    /// tolerant `if let Some(addr) = ..` guard).
    fn test_core(
        name: PublicKey,
        committee: Committee,
        path_suffix: &str,
    ) -> (SimpleItCore, Receiver<Header>) {
        let path = format!(".db_test_simpleit_commit_queue_{}", path_suffix);
        let _ = std::fs::remove_dir_all(&path);
        let store = Store::new(&path).expect("store opens");
        let registry = prometheus::Registry::new();
        let (metrics, _reporter) = Metrics::new(&registry);
        let (tx_output, rx_output) = channel(16);
        let (core, _rx_simpleit, _rx_payload_ready, _tx_simpleit, _ack_aggregator) =
            SimpleItCore::build(
                name,
                committee,
                Parameters::default(),
                store,
                Some(metrics),
                tx_output,
            );
        (core, rx_output)
    }

    async fn mark_payload(store: &mut Store, digest: &Digest, worker_id: WorkerId) {
        let key = [digest.as_ref(), &worker_id.to_le_bytes()].concat();
        store.write(key, Vec::new()).await;
    }

    fn served_payload_header(core: &SimpleItCore, author: PublicKey) -> (Header, Digest, Digest) {
        let missing = Digest([0x31; 32]);
        let present = Digest([0x32; 32]);
        let mut payload = BTreeMap::new();
        payload.insert(missing.clone(), 0);
        payload.insert(present.clone(), 0);
        (
            Header::new_vantage(author, 1, payload, core.genesis.clone(), core.sid.clone()),
            missing,
            present,
        )
    }

    fn sync_effect(effects: &[Effect]) -> Option<&Effect> {
        effects
            .iter()
            .find(|effect| matches!(effect, Effect::SyncBatches(..)))
    }

    #[tokio::test]
    async fn accepted_served_header_syncs_only_missing_payloads() {
        let committee = crate::common::committee();
        let keys: Vec<PublicKey> = committee.authorities.keys().cloned().collect();
        let (mut core, _) = test_core(keys[0], committee, "serve_missing");
        let (header, missing, present) = served_payload_header(&core, keys[1]);
        let mut store = core.lm.store_for_test();
        mark_payload(&mut store, &present, 0).await;
        core.rep.authorize((keys[1], 1, header.id.clone()));

        let effects = core.serve_effects(header.clone()).await;
        assert!(matches!(
            sync_effect(&effects),
            Some(Effect::SyncBatches(a, h, entries))
                if *a == keys[1] && h == &header.id && entries == &vec![(missing, 0)]
        ));
        assert!(
            !core
                .lm
                .blocks_handle()
                .lock()
                .get(&header.id)
                .unwrap()
                .payload_ok
        );
    }

    #[tokio::test]
    async fn duplicate_accepted_serve_merges_pending_payload_without_duplicate_waiters() {
        let committee = crate::common::committee();
        let keys: Vec<PublicKey> = committee.authorities.keys().cloned().collect();
        let (mut core, _) = test_core(keys[0], committee, "serve_duplicate");
        let (header, missing, first_arrival) = served_payload_header(&core, keys[1]);
        let mut store = core.lm.store_for_test();
        let (payload_tx, mut payload_rx) = channel(4);
        core.payload.tx_payload_ready = payload_tx;
        core.wire.worker_addresses.clear();
        core.rep.authorize((keys[1], 1, header.id.clone()));

        let effects = core.serve_effects(header.clone()).await;
        core.execute(effects).await;

        mark_payload(&mut store, &first_arrival, 0).await;
        let arrived = tokio::time::timeout(Duration::from_secs(1), payload_rx.recv())
            .await
            .expect("first payload waiter resolves")
            .expect("payload-ready channel stays open");
        assert_eq!(arrived, (header.id.clone(), first_arrival.clone(), 0));

        // Keep the first arrival unconsumed by `on_payload_ready`, then repeat the
        // accepted serve. The pending set must be unioned, not replaced by the fresh
        // store probe's one-key result.
        let effects = core.serve_effects(header.clone()).await;
        assert!(matches!(
            sync_effect(&effects),
            Some(Effect::SyncBatches(a, h, entries))
                if *a == keys[1]
                    && h == &header.id
                    && entries == &vec![(missing.clone(), 0)]
        ));
        core.execute(effects).await;

        {
            let pending = core
                .payload
                .pending_payload
                .get(&header.id)
                .expect("header remains pending");
            assert_eq!(pending.len(), 2);
            assert!(pending.contains(&(first_arrival, 0)));
            assert!(pending.contains(&(missing.clone(), 0)));
        }

        mark_payload(&mut store, &missing, 0).await;
        let arrived = tokio::time::timeout(Duration::from_secs(1), payload_rx.recv())
            .await
            .expect("last payload waiter resolves")
            .expect("payload-ready channel stays open");
        assert_eq!(arrived, (header.id, missing, 0));
        assert!(
            tokio::time::timeout(Duration::from_millis(50), payload_rx.recv())
                .await
                .is_err(),
            "a duplicate serve must not spawn a second waiter for the same payload"
        );
    }

    #[tokio::test]
    async fn rejected_served_header_emits_no_payload_sync() {
        let committee = crate::common::committee();
        let keys: Vec<PublicKey> = committee.authorities.keys().cloned().collect();
        let (mut core, _) = test_core(keys[0], committee, "serve_rejected");
        let mut header = Header::new_vantage(
            keys[1],
            1,
            BTreeMap::new(),
            core.genesis.clone(),
            core.sid.clone(),
        );
        header.id = Digest([0xee; 32]);
        core.rep.authorize((keys[1], 1, header.id.clone()));

        let effects = core.serve_effects(header).await;
        assert!(effects.is_empty());
    }

    #[tokio::test]
    async fn fully_present_served_header_emits_no_payload_sync() {
        let committee = crate::common::committee();
        let keys: Vec<PublicKey> = committee.authorities.keys().cloned().collect();
        let (mut core, _) = test_core(keys[0], committee, "serve_present");
        let (mut header, _missing, present) = served_payload_header(&core, keys[1]);
        header.payload.retain(|digest, _| digest == &present);
        header.id = header.digest();
        let mut store = core.lm.store_for_test();
        mark_payload(&mut store, &present, 0).await;
        core.rep.authorize((keys[1], 1, header.id.clone()));

        let effects = core.serve_effects(header.clone()).await;
        assert!(sync_effect(&effects).is_none());
        assert!(
            !core
                .lm
                .blocks_handle()
                .lock()
                .get(&header.id)
                .unwrap()
                .payload_ok
        );
    }

    /// `n` chain-linked headers for `author`, heights `1..=n`, NOT inserted into any
    /// `BlockCache` -- callers insert whichever prefix they want "locally available"
    /// via `insert` below.
    fn chain(author: PublicKey, n: Height, sid: &Digest, genesis: &Digest) -> Vec<Header> {
        let mut headers = Vec::new();
        let mut prev = genesis.clone();
        for height in 1..=n {
            let header = Header::new_vantage(author, height, BTreeMap::new(), prev, sid.clone());
            prev = header.id.clone();
            headers.push(header);
        }
        headers
    }

    /// Seeds `core`'s `BlockCache` directly with `header`, bypassing the full
    /// publish/repair pipeline -- `direct`/`payload_ok` are irrelevant to
    /// `collect_verified_suffix` (only `block_ok_verified` and the pinned
    /// author/height chain matter), so both are just set `true` for simplicity.
    fn insert(core: &SimpleItCore, header: &Header) {
        core.lm
            .blocks_handle()
            .lock()
            .upsert(header.clone(), true, true, true, true);
    }

    fn cut(entries: &[(PublicKey, &Header)]) -> Cut {
        entries
            .iter()
            .map(|(author, header)| {
                (
                    *author,
                    Proposal {
                        header_digest: header.id.clone(),
                        height: header.height,
                    },
                )
            })
            .collect()
    }

    /// A round whose author's suffix is unavailable emits nothing and stays queued.
    #[tokio::test]
    async fn commit_queue_blocks_on_unavailable_author_suffix_and_stays_queued() {
        let committee = committee_of(4);
        let keys: Vec<PublicKey> = committee.authorities.keys().cloned().collect();
        let (mut core, mut rx_output) = test_core(keys[0], committee, "unavailable");

        let author = keys[1];
        let chain_a = chain(author, 1, &core.sid.clone(), &core.genesis.clone());
        // Deliberately NOT inserted into BlockCache: chain_a[0] is "not yet available"
        // -- exactly the case `drain_commit_queue`'s doc comment describes: this node
        // may have recorded the committing round's proposal/certificate/decides
        // without ever having downloaded/verified this author's own chain.

        core.commit_queue.insert(1, cut(&[(author, &chain_a[0])]));
        core.drain_commit_queue().await;

        assert_eq!(core.commit_queue.len(), 1, "the round must stay queued");
        assert!(
            core.committed_watermark.is_empty(),
            "nothing should have advanced"
        );
        assert!(
            rx_output.try_recv().is_err(),
            "nothing should have been emitted"
        );
        assert_eq!(
            core.metrics
                .as_ref()
                .unwrap()
                .simpleit_commit_queue_len
                .get(),
            1,
            "the queue-depth gauge must reflect the stuck round"
        );
    }

    /// Once the missing blocks become available, the drain emits that round AND the
    /// subsequent queued round, in ascending round order, with each round's authors
    /// emitted together.
    #[tokio::test]
    async fn commit_queue_drains_in_round_order_once_unblocked_batching_authors_together() {
        let committee = committee_of(4);
        let keys: Vec<PublicKey> = committee.authorities.keys().cloned().collect();
        let (mut core, mut rx_output) = test_core(keys[0], committee, "drains_in_order");

        let sid = core.sid.clone();
        let genesis = core.genesis.clone();
        let author_a = keys[1];
        let author_b = keys[2];
        let chain_a = chain(author_a, 2, &sid, &genesis); // A@1, A@2
        let chain_b = chain(author_b, 1, &sid, &genesis); // B@1

        core.commit_queue
            .insert(1, cut(&[(author_a, &chain_a[0]), (author_b, &chain_b[0])]));
        core.commit_queue
            .insert(2, cut(&[(author_a, &chain_a[1]), (author_b, &chain_b[0])]));

        // Nothing inserted into BlockCache yet -- both rounds must stay queued.
        core.drain_commit_queue().await;
        assert_eq!(core.commit_queue.len(), 2);
        assert!(rx_output.try_recv().is_err());

        // Now the blocks arrive.
        insert(&core, &chain_a[0]);
        insert(&core, &chain_a[1]);
        insert(&core, &chain_b[0]);
        core.drain_commit_queue().await;

        assert!(
            core.commit_queue.is_empty(),
            "both rounds should have drained"
        );
        assert_eq!(
            core.committed_watermark.get(&author_a),
            Some(&(2, chain_a[1].id.clone()))
        );
        assert_eq!(
            core.committed_watermark.get(&author_b),
            Some(&(1, chain_b[0].id.clone()))
        );

        // Round 1: A@1 and B@1 emitted together (order within the round is
        // BTreeMap-author-order by construction, but this only asserts "together").
        let mut round1 = vec![
            rx_output.try_recv().expect("round 1's first header").id,
            rx_output.try_recv().expect("round 1's second header").id,
        ];
        round1.sort();
        let mut expected1 = vec![chain_a[0].id.clone(), chain_b[0].id.clone()];
        expected1.sort();
        assert_eq!(
            round1, expected1,
            "round 1's two authors must be emitted together"
        );

        // Round 2: only A@2 (B had nothing new that round).
        let round2 = rx_output.try_recv().expect("round 2's header");
        assert_eq!(round2.id, chain_a[1].id);

        assert!(
            rx_output.try_recv().is_err(),
            "nothing else should have been emitted"
        );
    }

    /// Two nodes processing the same commit sequence but receiving payloads in
    /// different orders produce the same emitted sequence -- the core safety property
    /// the audit fix restores. Node Y's blocks arrive in an order that would, under
    /// the old per-author-skip behaviour, have emitted round 3 (B's chain, fully
    /// available early) interleaved before round 1 (A's chain, available late); the
    /// fix instead blocks the whole queue on round 1 until it resolves.
    #[tokio::test]
    async fn commit_queue_emits_same_sequence_regardless_of_payload_arrival_order() {
        let committee = committee_of(4);
        let keys: Vec<PublicKey> = committee.authorities.keys().cloned().collect();

        let (mut node_x, mut rx_x) = test_core(keys[0], committee.clone(), "arrival_order_x");
        let (mut node_y, mut rx_y) = test_core(keys[0], committee, "arrival_order_y");

        let sid = node_x.sid.clone();
        let genesis = node_x.genesis.clone();
        let author_a = keys[1];
        let author_b = keys[2];
        let chain_a = chain(author_a, 2, &sid, &genesis);
        let chain_b = chain(author_b, 2, &sid, &genesis);

        let cut1 = cut(&[(author_a, &chain_a[0])]);
        let cut2 = cut(&[(author_a, &chain_a[1]), (author_b, &chain_b[0])]);
        let cut3 = cut(&[(author_b, &chain_b[1])]);

        for (round, c) in [(1, cut1.clone()), (2, cut2.clone()), (3, cut3.clone())] {
            node_x.commit_queue.insert(round, c.clone());
            node_y.commit_queue.insert(round, c);
        }

        // Node X: blocks arrive strictly in causal/round order.
        node_x.drain_commit_queue().await;
        insert(&node_x, &chain_a[0]);
        node_x.drain_commit_queue().await;
        insert(&node_x, &chain_a[1]);
        insert(&node_x, &chain_b[0]);
        node_x.drain_commit_queue().await;
        insert(&node_x, &chain_b[1]);
        node_x.drain_commit_queue().await;

        // Node Y: B's ENTIRE chain arrives first (out of its own causal order too --
        // height 2 lands before height 1), well before A's chain arrives at all.
        node_y.drain_commit_queue().await;
        insert(&node_y, &chain_b[1]);
        insert(&node_y, &chain_b[0]);
        node_y.drain_commit_queue().await;
        // B is now fully resolvable (rounds 2 and 3 both only need B, or B+A), but
        // round 1 (needing A@1) is still first in queue and still unresolved -- the
        // fix must block everything behind it, not skip ahead to round 3.
        assert!(
            rx_y.try_recv().is_err(),
            "round 1 blocking must suppress round 3 too, even though B is fully available"
        );
        assert_eq!(
            node_y.commit_queue.len(),
            3,
            "all three rounds must still be queued"
        );

        insert(&node_y, &chain_a[0]);
        insert(&node_y, &chain_a[1]);
        node_y.drain_commit_queue().await;

        assert!(node_x.commit_queue.is_empty());
        assert!(node_y.commit_queue.is_empty());

        let seq_x: Vec<Digest> =
            std::iter::from_fn(|| rx_x.try_recv().ok().map(|h| h.id)).collect();
        let seq_y: Vec<Digest> =
            std::iter::from_fn(|| rx_y.try_recv().ok().map(|h| h.id)).collect();
        let expected = vec![
            chain_a[0].id.clone(),
            chain_a[1].id.clone(),
            chain_b[0].id.clone(),
            chain_b[1].id.clone(),
        ];
        assert_eq!(seq_x, expected, "node X's emitted sequence");
        assert_eq!(
            seq_x, seq_y,
            "emitted sequence must be identical regardless of payload arrival order"
        );
    }
}
