[package]
name = "node"
version = "0.1.0"
authors = ["George Danezis <gdanezis@fb.com>"]
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec"] }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
bytes = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }

config = { path = "../config" }
store = { path = "../store" }
crypto = { path = "../crypto" }
primary = { path = "../primary" }
worker = { path = "../worker" }
metrics = { path = "../metrics" }
network = { path = "../network" }
prometheus = { workspace = true }

[features]
benchmark = ["worker/benchmark", "primary/benchmark"]

[[bin]]
name = "benchmark_client"
path = "src/benchmark_client.rs"
required-features = ["benchmark"]
