[package]
name = "worker"
version = "0.1.0"
authors = ["Alberto Sonnino <asonnino@fb.com>"]
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tokio-util = { workspace = true, features = ["codec"] }
blake3 = { workspace = true }
serde = { workspace = true }
bytes = { workspace = true }
log = { workspace = true }
bincode = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }

crypto = { path = "../crypto" }
store = { path = "../store" }
config = { path = "../config" }
network = { path = "../network" }
primary = { path = "../primary" }
metrics = { path = "../metrics" }
prometheus = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[features]
benchmark = []
