// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

//! Pluggable signature schemes for the Autobahn consensus/ordering path.
//!
//! The DAG/data path (headers, car dissemination) keeps using the Ed25519
//! identity key ([`crate::Signature`]). The *ordering* messages — car votes,
//! quorum certificates, PoA certificates, prepare/confirm/commit consensus
//! messages, and timeouts — instead carry a [`ConsensusSignature`], whose
//! scheme is fixed committee-wide by [`ConsensusSignatureScheme`].
//!
//! An authority's identity remains its Ed25519 public key. When a post-quantum
//! scheme is selected, each authority additionally holds a
//! [`ConsensusPublicKey`] (published in the committee) and the matching
//! [`ConsensusSecretKey`]. Ed25519 is the default and requires no extra keys;
//! its `ConsensusSignature` wraps the existing 64-byte [`crate::Signature`], so
//! the fast dalek batch-verification path is preserved for quorum certificates.
//!
//! Post-quantum schemes are implemented behind [`PqSignatureScheme`]; each is a
//! zero-sized marker type and the dispatch enums are generated by the
//! `consensus_signature_schemes!` macro. Adding a scheme is one macro line.

use std::{fmt, str::FromStr};

use base64::prelude::{Engine as _, BASE64_STANDARD};
use serde::{de, Deserialize, Deserializer, Serialize, Serializer};

use crate::{CryptoError, Digest, PublicKey, SecretKey, Signature};

// ---------------------------------------------------------------------------
// Generic post-quantum scheme abstraction
// ---------------------------------------------------------------------------

/// A digital-signature scheme usable for consensus authentication.
///
/// Implementors are zero-sized marker types. The signed message is always the
/// 32-byte consensus [`Digest`]. Encodings are the scheme's standard byte
/// encodings (FIPS 204 / FIPS 205).
pub trait PqSignatureScheme:
    Clone + Copy + fmt::Debug + PartialEq + Eq + Send + Sync + 'static
{
    /// Stable, lower-case, kebab-case identifier (CLI / config value).
    const NAME: &'static str;
    const PUBLIC_KEY_SIZE: usize;
    /// Size of the serialized private-key material.
    const SECRET_KEY_SIZE: usize;
    const SIGNATURE_SIZE: usize;

    type SigningKey: Clone + Send + Sync;
    type VerifyingKey: Clone + Send + Sync;

    fn keygen_from_seed(seed: &[u8; 32]) -> Self::SigningKey;
    fn signing_key_to_bytes(key: &Self::SigningKey) -> Vec<u8>;
    fn signing_key_from_bytes(bytes: &[u8]) -> Option<Self::SigningKey>;
    fn verifying_key(key: &Self::SigningKey) -> Self::VerifyingKey;
    fn verifying_key_to_bytes(key: &Self::VerifyingKey) -> Vec<u8>;
    fn verifying_key_from_bytes(bytes: &[u8]) -> Option<Self::VerifyingKey>;
    fn sign(key: &Self::SigningKey, message: &[u8]) -> Vec<u8>;
    fn verify(key: &Self::VerifyingKey, message: &[u8], signature: &[u8]) -> bool;
}

/// Private signing key of scheme `S`.
pub struct PqSigner<S: PqSignatureScheme>(Box<S::SigningKey>);
/// Public verifying key of scheme `S`, kept decoded for hot-path verification.
pub struct PqPublicKey<S: PqSignatureScheme>(S::VerifyingKey);

impl<S: PqSignatureScheme> PqSigner<S> {
    pub fn from_seed(seed: &[u8; 32]) -> Self {
        Self(Box::new(S::keygen_from_seed(seed)))
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, String> {
        if bytes.len() != S::SECRET_KEY_SIZE {
            return Err(format!(
                "invalid {} secret key length {} (expected {})",
                S::NAME,
                bytes.len(),
                S::SECRET_KEY_SIZE
            ));
        }
        S::signing_key_from_bytes(bytes)
            .map(|key| Self(Box::new(key)))
            .ok_or_else(|| format!("invalid {} secret key encoding", S::NAME))
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        S::signing_key_to_bytes(&self.0)
    }

    pub fn public_key(&self) -> PqPublicKey<S> {
        PqPublicKey(S::verifying_key(&self.0))
    }

    pub fn sign(&self, message: &[u8; 32]) -> Vec<u8> {
        let bytes = S::sign(&self.0, message);
        debug_assert_eq!(bytes.len(), S::SIGNATURE_SIZE);
        bytes
    }
}

impl<S: PqSignatureScheme> PqPublicKey<S> {
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, String> {
        if bytes.len() != S::PUBLIC_KEY_SIZE {
            return Err(format!(
                "invalid {} public key length {} (expected {})",
                S::NAME,
                bytes.len(),
                S::PUBLIC_KEY_SIZE
            ));
        }
        S::verifying_key_from_bytes(bytes)
            .map(Self)
            .ok_or_else(|| format!("invalid {} public key encoding", S::NAME))
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        S::verifying_key_to_bytes(&self.0)
    }

    pub fn verify(&self, message: &[u8; 32], signature: &[u8]) -> bool {
        signature.len() == S::SIGNATURE_SIZE && S::verify(&self.0, message, signature)
    }
}

impl<S: PqSignatureScheme> Clone for PqSigner<S> {
    fn clone(&self) -> Self {
        Self(self.0.clone())
    }
}
impl<S: PqSignatureScheme> Clone for PqPublicKey<S> {
    fn clone(&self) -> Self {
        Self(self.0.clone())
    }
}
impl<S: PqSignatureScheme> PartialEq for PqPublicKey<S> {
    fn eq(&self, other: &Self) -> bool {
        self.to_bytes() == other.to_bytes()
    }
}
impl<S: PqSignatureScheme> Eq for PqPublicKey<S> {}

impl<S: PqSignatureScheme> fmt::Debug for PqSigner<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}Signer(public_key={:?})", S::NAME, self.public_key())
    }
}
impl<S: PqSignatureScheme> fmt::Debug for PqPublicKey<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}Pk({})", S::NAME, hex::encode(&self.to_bytes()[..4]))
    }
}

// ---------------------------------------------------------------------------
// ML-DSA (FIPS 204) — RustCrypto `ml-dsa`
// ---------------------------------------------------------------------------

macro_rules! impl_ml_dsa_scheme {
    ($marker:ident, $params:ty, $name:literal, pk = $pk:literal, sig = $sig:literal) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct $marker;

        impl PqSignatureScheme for $marker {
            const NAME: &'static str = $name;
            const PUBLIC_KEY_SIZE: usize = $pk;
            /// ML-DSA private keys are stored as their 32-byte seed.
            const SECRET_KEY_SIZE: usize = 32;
            const SIGNATURE_SIZE: usize = $sig;

            type SigningKey = ml_dsa::SigningKey<$params>;
            type VerifyingKey = ml_dsa::VerifyingKey<$params>;

            fn keygen_from_seed(seed: &[u8; 32]) -> Self::SigningKey {
                ml_dsa::SigningKey::<$params>::from_seed(&ml_dsa::Seed::from(*seed))
            }
            fn signing_key_to_bytes(key: &Self::SigningKey) -> Vec<u8> {
                key.to_seed().to_vec()
            }
            fn signing_key_from_bytes(bytes: &[u8]) -> Option<Self::SigningKey> {
                let seed: [u8; 32] = bytes.try_into().ok()?;
                Some(Self::keygen_from_seed(&seed))
            }
            fn verifying_key(key: &Self::SigningKey) -> Self::VerifyingKey {
                ml_dsa::Keypair::verifying_key(key)
            }
            fn verifying_key_to_bytes(key: &Self::VerifyingKey) -> Vec<u8> {
                key.encode().to_vec()
            }
            fn verifying_key_from_bytes(bytes: &[u8]) -> Option<Self::VerifyingKey> {
                let encoded = ml_dsa::EncodedVerifyingKey::<$params>::try_from(bytes).ok()?;
                Some(ml_dsa::VerifyingKey::<$params>::decode(&encoded))
            }
            fn sign(key: &Self::SigningKey, message: &[u8]) -> Vec<u8> {
                let signature: ml_dsa::Signature<$params> = ml_dsa::Signer::sign(key, message);
                signature.encode().to_vec()
            }
            fn verify(key: &Self::VerifyingKey, message: &[u8], signature: &[u8]) -> bool {
                let Ok(signature) = ml_dsa::Signature::<$params>::try_from(signature) else {
                    return false;
                };
                ml_dsa::Verifier::verify(key, message, &signature).is_ok()
            }
        }
    };
}

impl_ml_dsa_scheme!(
    MlDsa44,
    ml_dsa::MlDsa44,
    "ml-dsa-44",
    pk = 1_312,
    sig = 2_420
);
impl_ml_dsa_scheme!(
    MlDsa65,
    ml_dsa::MlDsa65,
    "ml-dsa-65",
    pk = 1_952,
    sig = 3_309
);
impl_ml_dsa_scheme!(
    MlDsa87,
    ml_dsa::MlDsa87,
    "ml-dsa-87",
    pk = 2_592,
    sig = 4_627
);

// ---------------------------------------------------------------------------
// SLH-DSA (FIPS 205) — RustCrypto `slh-dsa`
// ---------------------------------------------------------------------------

macro_rules! impl_slh_dsa_scheme {
    ($marker:ident, $params:ty, $name:literal, n = $n:literal, sig = $sig:literal) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct $marker;

        impl PqSignatureScheme for $marker {
            const NAME: &'static str = $name;
            const PUBLIC_KEY_SIZE: usize = 2 * $n;
            const SECRET_KEY_SIZE: usize = 4 * $n;
            const SIGNATURE_SIZE: usize = $sig;

            type SigningKey = slh_dsa::SigningKey<$params>;
            type VerifyingKey = slh_dsa::VerifyingKey<$params>;

            fn keygen_from_seed(seed: &[u8; 32]) -> Self::SigningKey {
                // FIPS 205 keygen from (SK.seed, SK.prf, PK.seed).
                let mut material = [0u8; 3 * $n];
                expand_seed($name, seed, &mut material);
                let (sk_seed, rest) = material.split_at($n);
                let (sk_prf, pk_seed) = rest.split_at($n);
                slh_dsa::SigningKey::<$params>::slh_keygen_internal(sk_seed, sk_prf, pk_seed)
            }
            fn signing_key_to_bytes(key: &Self::SigningKey) -> Vec<u8> {
                key.to_vec()
            }
            fn signing_key_from_bytes(bytes: &[u8]) -> Option<Self::SigningKey> {
                slh_dsa::SigningKey::<$params>::try_from(bytes).ok()
            }
            fn verifying_key(key: &Self::SigningKey) -> Self::VerifyingKey {
                slh_dsa::signature::Keypair::verifying_key(key)
            }
            fn verifying_key_to_bytes(key: &Self::VerifyingKey) -> Vec<u8> {
                key.to_vec()
            }
            fn verifying_key_from_bytes(bytes: &[u8]) -> Option<Self::VerifyingKey> {
                slh_dsa::VerifyingKey::<$params>::try_from(bytes).ok()
            }
            fn sign(key: &Self::SigningKey, message: &[u8]) -> Vec<u8> {
                let signature: slh_dsa::Signature<$params> =
                    slh_dsa::signature::Signer::try_sign(key, message)
                        .expect("SLH-DSA signing is infallible for a valid key");
                slh_dsa::signature::SignatureEncoding::to_vec(&signature)
            }
            fn verify(key: &Self::VerifyingKey, message: &[u8], signature: &[u8]) -> bool {
                let Ok(signature) = slh_dsa::Signature::<$params>::try_from(signature) else {
                    return false;
                };
                slh_dsa::signature::Verifier::verify(key, message, &signature).is_ok()
            }
        }
    };
}

impl_slh_dsa_scheme!(
    SlhDsaSha2_128s,
    slh_dsa::Sha2_128s,
    "slh-dsa-sha2-128s",
    n = 16,
    sig = 7_856
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_128f,
    slh_dsa::Sha2_128f,
    "slh-dsa-sha2-128f",
    n = 16,
    sig = 17_088
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_192s,
    slh_dsa::Sha2_192s,
    "slh-dsa-sha2-192s",
    n = 24,
    sig = 16_224
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_192f,
    slh_dsa::Sha2_192f,
    "slh-dsa-sha2-192f",
    n = 24,
    sig = 35_664
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_256s,
    slh_dsa::Sha2_256s,
    "slh-dsa-sha2-256s",
    n = 32,
    sig = 29_792
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_256f,
    slh_dsa::Sha2_256f,
    "slh-dsa-sha2-256f",
    n = 32,
    sig = 49_856
);

/// Generate a fresh consensus keypair for `scheme` from OS randomness.
/// Returns `None` for Ed25519, which reuses the node's identity key.
pub fn generate_consensus_keypair(
    scheme: ConsensusSignatureScheme,
) -> Option<(ConsensusPublicKey, ConsensusSecretKey)> {
    use rand::RngCore as _;
    let mut seed = [0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut seed);
    let secret = ConsensusSecretKey::from_seed(scheme, &seed)?;
    Some((secret.public_key(), secret))
}

/// Deterministic per-authority seed for benchmark and test key material,
/// domain-separated by scheme.
pub fn benchmark_seed(scheme: ConsensusSignatureScheme, authority: u64) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new_derive_key("vantage consensus authentication seed");
    hasher.update(scheme.name().as_bytes());
    hasher.update(&authority.to_le_bytes());
    hasher.finalize().into()
}

/// Derive a signing key for `scheme` from a 32-byte seed. Ed25519 returns
/// `None` (it reuses the node's identity key).
pub fn consensus_secret_from_seed(
    scheme: ConsensusSignatureScheme,
    seed: &[u8; 32],
) -> Option<ConsensusSecretKey> {
    ConsensusSecretKey::from_seed(scheme, seed)
}

fn expand_seed(scheme_name: &str, seed: &[u8; 32], output: &mut [u8]) {
    let mut hasher = blake3::Hasher::new_derive_key("vantage consensus key expansion");
    hasher.update(scheme_name.as_bytes());
    hasher.update(seed);
    hasher.finalize_xof().fill(output);
}

// ---------------------------------------------------------------------------
// Scheme registry — the single place listing every post-quantum scheme.
// ---------------------------------------------------------------------------

macro_rules! consensus_signature_schemes {
    ($( $variant:ident($scheme:ty, $name:literal) ),+ $(,)?) => {
        /// Signature scheme authenticating the Autobahn consensus/ordering path
        /// (committee-wide; committee field `consensus_signature_scheme`).
        #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
        pub enum ConsensusSignatureScheme {
            #[default]
            #[serde(rename = "ed25519")]
            Ed25519,
            $( #[serde(rename = $name)] $variant, )+
        }

        impl ConsensusSignatureScheme {
            pub const ALL: &'static [Self] = &[Self::Ed25519, $( Self::$variant, )+];

            pub fn name(self) -> &'static str {
                match self {
                    Self::Ed25519 => "ed25519",
                    $( Self::$variant => <$scheme>::NAME, )+
                }
            }

            pub fn is_post_quantum(self) -> bool {
                !matches!(self, Self::Ed25519)
            }

            pub fn public_key_size(self) -> usize {
                match self {
                    Self::Ed25519 => 32,
                    $( Self::$variant => <$scheme>::PUBLIC_KEY_SIZE, )+
                }
            }

            pub fn signature_size(self) -> usize {
                match self {
                    Self::Ed25519 => 64,
                    $( Self::$variant => <$scheme>::SIGNATURE_SIZE, )+
                }
            }
        }

        /// Post-quantum public key of one authority for the selected scheme.
        #[derive(Clone, Debug, PartialEq, Eq)]
        pub enum ConsensusPublicKey {
            $( $variant(PqPublicKey<$scheme>), )+
        }

        impl ConsensusPublicKey {
            pub fn scheme(&self) -> ConsensusSignatureScheme {
                match self { $( Self::$variant(_) => ConsensusSignatureScheme::$variant, )+ }
            }
            pub fn from_bytes(scheme: ConsensusSignatureScheme, bytes: &[u8]) -> Result<Self, String> {
                match scheme {
                    ConsensusSignatureScheme::Ed25519 =>
                        Err("ed25519 uses the authority identity key".into()),
                    $( ConsensusSignatureScheme::$variant =>
                        PqPublicKey::<$scheme>::from_bytes(bytes).map(Self::$variant), )+
                }
            }
            pub fn to_bytes(&self) -> Vec<u8> {
                match self { $( Self::$variant(k) => k.to_bytes(), )+ }
            }
            fn verify_pq(&self, message: &[u8; 32], signature: &[u8]) -> bool {
                match self { $( Self::$variant(k) => k.verify(message, signature), )+ }
            }
        }

        /// Post-quantum signing key of this node for the selected scheme.
        #[derive(Clone, Debug)]
        pub enum ConsensusSecretKey {
            $( $variant(PqSigner<$scheme>), )+
        }

        impl ConsensusSecretKey {
            pub fn from_seed(scheme: ConsensusSignatureScheme, seed: &[u8; 32]) -> Option<Self> {
                match scheme {
                    ConsensusSignatureScheme::Ed25519 => None,
                    $( ConsensusSignatureScheme::$variant =>
                        Some(Self::$variant(PqSigner::<$scheme>::from_seed(seed))), )+
                }
            }
            pub fn from_bytes(scheme: ConsensusSignatureScheme, bytes: &[u8]) -> Result<Self, String> {
                match scheme {
                    ConsensusSignatureScheme::Ed25519 =>
                        Err("ed25519 uses the authority identity key".into()),
                    $( ConsensusSignatureScheme::$variant =>
                        PqSigner::<$scheme>::from_bytes(bytes).map(Self::$variant), )+
                }
            }
            pub fn scheme(&self) -> ConsensusSignatureScheme {
                match self { $( Self::$variant(_) => ConsensusSignatureScheme::$variant, )+ }
            }
            pub fn to_bytes(&self) -> Vec<u8> {
                match self { $( Self::$variant(k) => k.to_bytes(), )+ }
            }
            pub fn public_key(&self) -> ConsensusPublicKey {
                match self { $( Self::$variant(k) => ConsensusPublicKey::$variant(k.public_key()), )+ }
            }
            fn sign_pq(&self, message: &[u8; 32]) -> Vec<u8> {
                match self { $( Self::$variant(k) => k.sign(message), )+ }
            }
        }
    };
}

consensus_signature_schemes! {
    MlDsa44(MlDsa44, "ml-dsa-44"),
    MlDsa65(MlDsa65, "ml-dsa-65"),
    MlDsa87(MlDsa87, "ml-dsa-87"),
    SlhDsaSha2_128s(SlhDsaSha2_128s, "slh-dsa-sha2-128s"),
    SlhDsaSha2_128f(SlhDsaSha2_128f, "slh-dsa-sha2-128f"),
    SlhDsaSha2_192s(SlhDsaSha2_192s, "slh-dsa-sha2-192s"),
    SlhDsaSha2_192f(SlhDsaSha2_192f, "slh-dsa-sha2-192f"),
    SlhDsaSha2_256s(SlhDsaSha2_256s, "slh-dsa-sha2-256s"),
    SlhDsaSha2_256f(SlhDsaSha2_256f, "slh-dsa-sha2-256f"),
}

impl fmt::Display for ConsensusSignatureScheme {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

impl FromStr for ConsensusSignatureScheme {
    type Err = String;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .iter()
            .copied()
            .find(|s| s.name() == value)
            .ok_or_else(|| {
                let names: Vec<_> = Self::ALL.iter().map(|s| s.name()).collect();
                format!(
                    "unknown consensus signature scheme '{value}'; expected one of: {}",
                    names.join(", ")
                )
            })
    }
}

/// `true` for the slow-signing SLH-DSA `…s` parameter sets. They are exposed
/// for completeness but sign at ~80–150 ms, far too slow for the per-vote
/// consensus path; callers may warn.
pub fn is_slow_signing(scheme: ConsensusSignatureScheme) -> bool {
    matches!(
        scheme,
        ConsensusSignatureScheme::SlhDsaSha2_128s
            | ConsensusSignatureScheme::SlhDsaSha2_192s
            | ConsensusSignatureScheme::SlhDsaSha2_256s
    )
}

// ---------------------------------------------------------------------------
// ConsensusSignature — the proof carried by ordering messages
// ---------------------------------------------------------------------------

/// A signature on the consensus/ordering path. `Ed25519` wraps the existing
/// 64-byte identity-key signature (preserving dalek batch verification);
/// `PostQuantum` carries the scheme-encoded bytes, validated on verify against
/// the author's [`ConsensusPublicKey`].
#[derive(Clone)]
pub enum ConsensusSignature {
    Ed25519(Signature),
    PostQuantum(Box<[u8]>),
}

impl PartialEq for ConsensusSignature {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Ed25519(a), Self::Ed25519(b)) => a.to_bytes() == b.to_bytes(),
            (Self::PostQuantum(a), Self::PostQuantum(b)) => a == b,
            _ => false,
        }
    }
}
impl Eq for ConsensusSignature {}

impl Default for ConsensusSignature {
    fn default() -> Self {
        Self::Ed25519(Signature::default())
    }
}

impl fmt::Debug for ConsensusSignature {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Ed25519(_) => write!(f, "ed25519-sig"),
            Self::PostQuantum(bytes) => {
                write!(f, "pq-sig({})", hex::encode(&bytes[..bytes.len().min(4)]))
            }
        }
    }
}

impl ConsensusSignature {
    /// Sign `digest` with this node's consensus key material. The Ed25519
    /// identity secret is always available; `pq_secret` must be present for a
    /// post-quantum scheme.
    pub fn sign(
        digest: &Digest,
        identity_secret: &SecretKey,
        pq_secret: Option<&ConsensusSecretKey>,
    ) -> Self {
        match pq_secret {
            None => Self::Ed25519(Signature::new(digest, identity_secret)),
            Some(secret) => Self::PostQuantum(secret.sign_pq(&digest.0).into_boxed_slice()),
        }
    }

    /// Verify against `author` for `scheme`. Ed25519 uses the identity public
    /// key; post-quantum uses `pq_public` (the author's committee entry).
    pub fn verify(
        &self,
        digest: &Digest,
        author: &PublicKey,
        scheme: ConsensusSignatureScheme,
        pq_public: Option<&ConsensusPublicKey>,
    ) -> Result<(), ConsensusVerifyError> {
        match (scheme, self) {
            (ConsensusSignatureScheme::Ed25519, Self::Ed25519(sig)) => sig
                .verify(digest, author)
                .map_err(ConsensusVerifyError::Ed25519),
            (scheme, Self::PostQuantum(bytes)) if scheme.is_post_quantum() => {
                let key = pq_public.ok_or(ConsensusVerifyError::MissingKey)?;
                if key.scheme() != scheme {
                    return Err(ConsensusVerifyError::SchemeMismatch);
                }
                if key.verify_pq(&digest.0, bytes) {
                    Ok(())
                } else {
                    Err(ConsensusVerifyError::Invalid)
                }
            }
            _ => Err(ConsensusVerifyError::SchemeMismatch),
        }
    }

    /// The Ed25519 inner signature, if this is an Ed25519 proof. Used by the
    /// dalek batch-verification fast path.
    pub fn as_ed25519(&self) -> Option<&Signature> {
        match self {
            Self::Ed25519(sig) => Some(sig),
            Self::PostQuantum(_) => None,
        }
    }

    /// Canonical `tag || payload` encoding, identical to the wire encoding.
    /// Used wherever a digest must bind the exact signature bytes.
    pub fn to_canonical_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        match self {
            Self::Ed25519(sig) => {
                bytes.push(0u8);
                bytes.extend_from_slice(&sig.to_bytes());
            }
            Self::PostQuantum(payload) => {
                bytes.push(1u8);
                bytes.extend_from_slice(payload);
            }
        }
        bytes
    }
}

/// Verify a quorum of consensus signatures over a single `digest`. Ed25519
/// committees use dalek batch verification; post-quantum committees verify each
/// signature independently (no cross-key batching exists for ML-DSA/SLH-DSA).
pub fn verify_quorum<'a, I, F>(
    digest: &Digest,
    scheme: ConsensusSignatureScheme,
    votes: I,
    pq_public: F,
) -> Result<(), ConsensusVerifyError>
where
    I: IntoIterator<Item = &'a (PublicKey, ConsensusSignature)>,
    F: Fn(&PublicKey) -> Option<&'a ConsensusPublicKey>,
{
    if scheme.is_post_quantum() {
        for (author, sig) in votes {
            sig.verify(digest, author, scheme, pq_public(author))?;
        }
        return Ok(());
    }
    let mut ed = Vec::new();
    for (author, sig) in votes {
        match sig.as_ed25519() {
            Some(inner) => ed.push((*author, inner.clone())),
            None => return Err(ConsensusVerifyError::SchemeMismatch),
        }
    }
    Signature::verify_batch(digest, &ed).map_err(ConsensusVerifyError::Ed25519)
}

/// Like [`verify_quorum`] but each vote authenticates its own `digests[i]`.
pub fn verify_quorum_multi<'a, I, F>(
    digests: &[Digest],
    scheme: ConsensusSignatureScheme,
    votes: I,
    pq_public: F,
) -> Result<(), ConsensusVerifyError>
where
    I: IntoIterator<Item = &'a (PublicKey, ConsensusSignature)>,
    F: Fn(&PublicKey) -> Option<&'a ConsensusPublicKey>,
{
    if scheme.is_post_quantum() {
        for (i, (author, sig)) in votes.into_iter().enumerate() {
            sig.verify(&digests[i], author, scheme, pq_public(author))?;
        }
        return Ok(());
    }
    let mut ed = Vec::new();
    for (author, sig) in votes {
        match sig.as_ed25519() {
            Some(inner) => ed.push((*author, inner.clone())),
            None => return Err(ConsensusVerifyError::SchemeMismatch),
        }
    }
    Signature::verify_batch_multi(digests, &ed).map_err(ConsensusVerifyError::Ed25519)
}

// ---------------------------------------------------------------------------
// Key file encodings: `"<scheme>:<base64>"` strings, matching the committee
// and keypair JSON files' human-readable style.
// ---------------------------------------------------------------------------

fn serialize_scheme_key<S: Serializer>(
    scheme: ConsensusSignatureScheme,
    bytes: &[u8],
    serializer: S,
) -> Result<S::Ok, S::Error> {
    serializer.serialize_str(&format!("{scheme}:{}", BASE64_STANDARD.encode(bytes)))
}

fn parse_scheme_key<E: de::Error>(value: &str) -> Result<(ConsensusSignatureScheme, Vec<u8>), E> {
    let (scheme, payload) = value
        .split_once(':')
        .ok_or_else(|| E::custom("expected '<scheme>:<base64>'"))?;
    let scheme = ConsensusSignatureScheme::from_str(scheme).map_err(E::custom)?;
    let bytes = BASE64_STANDARD
        .decode(payload)
        .map_err(|e| E::custom(format!("invalid base64 key encoding: {e}")))?;
    Ok((scheme, bytes))
}

impl Serialize for ConsensusPublicKey {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serialize_scheme_key(self.scheme(), &self.to_bytes(), serializer)
    }
}

impl<'de> Deserialize<'de> for ConsensusPublicKey {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        let (scheme, bytes) = parse_scheme_key(&value)?;
        Self::from_bytes(scheme, &bytes).map_err(de::Error::custom)
    }
}

impl Serialize for ConsensusSecretKey {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serialize_scheme_key(self.scheme(), &self.to_bytes(), serializer)
    }
}

impl<'de> Deserialize<'de> for ConsensusSecretKey {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        let (scheme, bytes) = parse_scheme_key(&value)?;
        Self::from_bytes(scheme, &bytes).map_err(de::Error::custom)
    }
}

#[derive(Debug)]
pub enum ConsensusVerifyError {
    Ed25519(CryptoError),
    /// The carried proof's scheme does not match the committee scheme.
    SchemeMismatch,
    /// A post-quantum public key for the author is not in the committee.
    MissingKey,
    /// The post-quantum signature failed verification.
    Invalid,
}

impl fmt::Display for ConsensusVerifyError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Ed25519(e) => write!(f, "ed25519 verification failed: {e}"),
            Self::SchemeMismatch => write!(f, "consensus signature scheme mismatch"),
            Self::MissingKey => write!(f, "missing post-quantum consensus key for author"),
            Self::Invalid => write!(f, "post-quantum consensus signature is invalid"),
        }
    }
}
impl std::error::Error for ConsensusVerifyError {}

// ---------------------------------------------------------------------------
// Wire encoding: `scheme tag (u8) || payload`. Ed25519 tag = 0.
// ---------------------------------------------------------------------------

impl Serialize for ConsensusSignature {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let mut bytes = Vec::new();
        match self {
            Self::Ed25519(sig) => {
                bytes.push(0u8);
                bytes.extend_from_slice(&sig.to_bytes());
            }
            Self::PostQuantum(payload) => {
                bytes.push(1u8);
                bytes.extend_from_slice(payload);
            }
        }
        serializer.serialize_bytes(&bytes)
    }
}

impl<'de> Deserialize<'de> for ConsensusSignature {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct V;
        impl<'de> de::Visitor<'de> for V {
            type Value = ConsensusSignature;
            fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str("a tagged consensus signature")
            }
            fn visit_bytes<E: de::Error>(self, v: &[u8]) -> Result<Self::Value, E> {
                let (&tag, payload) = v
                    .split_first()
                    .ok_or_else(|| E::custom("empty signature"))?;
                match tag {
                    0 => {
                        let bytes: [u8; 64] = payload
                            .try_into()
                            .map_err(|_| E::custom("invalid ed25519 signature length"))?;
                        Ok(ConsensusSignature::Ed25519(Signature::from_bytes(&bytes)))
                    }
                    1 => Ok(ConsensusSignature::PostQuantum(payload.into())),
                    other => Err(E::custom(format!(
                        "unknown consensus signature tag {other}"
                    ))),
                }
            }
            fn visit_byte_buf<E: de::Error>(self, v: Vec<u8>) -> Result<Self::Value, E> {
                self.visit_bytes(&v)
            }
            fn visit_seq<A: de::SeqAccess<'de>>(self, mut seq: A) -> Result<Self::Value, A::Error> {
                let mut bytes = Vec::new();
                while let Some(b) = seq.next_element::<u8>()? {
                    bytes.push(b);
                }
                self.visit_bytes(&bytes)
            }
        }
        deserializer.deserialize_bytes(V)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generate_production_keypair;

    fn digest(byte: u8) -> Digest {
        Digest([byte; 32])
    }

    #[test]
    fn scheme_names_round_trip() {
        for &scheme in ConsensusSignatureScheme::ALL {
            assert_eq!(
                scheme.name().parse::<ConsensusSignatureScheme>().unwrap(),
                scheme
            );
            let json = serde_json::to_string(&scheme).unwrap();
            assert_eq!(json.trim_matches('"'), scheme.name());
            assert_eq!(
                serde_json::from_str::<ConsensusSignatureScheme>(&json).unwrap(),
                scheme
            );
        }
        assert!("rsa".parse::<ConsensusSignatureScheme>().is_err());
        assert_eq!(
            ConsensusSignatureScheme::default(),
            ConsensusSignatureScheme::Ed25519
        );
    }

    #[test]
    fn ed25519_sign_verify_and_batch() {
        let (name, secret) = generate_production_keypair();
        let d = digest(1);
        let sig = ConsensusSignature::sign(&d, &secret, None);
        assert!(sig
            .verify(&d, &name, ConsensusSignatureScheme::Ed25519, None)
            .is_ok());
        assert!(sig
            .verify(&digest(2), &name, ConsensusSignatureScheme::Ed25519, None)
            .is_err());

        let votes = vec![(name, sig.clone())];
        assert!(verify_quorum(&d, ConsensusSignatureScheme::Ed25519, &votes, |_| None).is_ok());
    }

    #[test]
    fn post_quantum_sign_verify_reject_and_quorum() {
        for &scheme in ConsensusSignatureScheme::ALL {
            if !scheme.is_post_quantum() {
                continue;
            }
            // Two authorities with distinct identity + PQ keys.
            let (name0, id0) = generate_production_keypair();
            let (name1, id1) = generate_production_keypair();
            let sk0 = ConsensusSecretKey::from_seed(scheme, &benchmark_seed(scheme, 0)).unwrap();
            let sk1 = ConsensusSecretKey::from_seed(scheme, &benchmark_seed(scheme, 1)).unwrap();
            let pk0 = sk0.public_key();
            let pk1 = sk1.public_key();
            assert_eq!(pk0.scheme(), scheme);
            assert_ne!(pk0, pk1);

            let d = digest(7);
            let s0 = ConsensusSignature::sign(&d, &id0, Some(&sk0));
            let s1 = ConsensusSignature::sign(&d, &id1, Some(&sk1));
            assert!(
                s0.verify(&d, &name0, scheme, Some(&pk0)).is_ok(),
                "{scheme}"
            );
            // wrong digest, wrong key, missing key, scheme mismatch all rejected
            assert!(s0.verify(&digest(8), &name0, scheme, Some(&pk0)).is_err());
            assert!(s0.verify(&d, &name0, scheme, Some(&pk1)).is_err());
            assert!(s0.verify(&d, &name0, scheme, None).is_err());
            assert!(s0
                .verify(&d, &name0, ConsensusSignatureScheme::Ed25519, None)
                .is_err());

            // Deterministic signing and size.
            assert_eq!(
                match &s0 {
                    ConsensusSignature::PostQuantum(b) => b.len(),
                    _ => 0,
                },
                scheme.signature_size(),
                "{scheme}"
            );

            // Quorum over one digest, keyed by author.
            let keys = [(name0, pk0.clone()), (name1, pk1.clone())];
            let lookup = |a: &PublicKey| keys.iter().find(|(n, _)| n == a).map(|(_, k)| k);
            let votes = vec![(name0, s0), (name1, s1)];
            assert!(
                verify_quorum(&d, scheme, &votes, lookup).is_ok(),
                "{scheme}"
            );

            // serde round-trip of a PQ signature.
            let enc = bincode::serialize(&votes[0].1).unwrap();
            let dec: ConsensusSignature = bincode::deserialize(&enc).unwrap();
            assert_eq!(dec, votes[0].1);
        }
    }

    #[test]
    fn key_encodings_round_trip() {
        for &scheme in ConsensusSignatureScheme::ALL {
            let Some(sk) = ConsensusSecretKey::from_seed(scheme, &benchmark_seed(scheme, 3)) else {
                continue;
            };
            let pk = sk.public_key();
            assert_eq!(pk.to_bytes().len(), scheme.public_key_size());
            let sk2 = ConsensusSecretKey::from_bytes(scheme, &sk.to_bytes()).unwrap();
            assert_eq!(sk2.public_key(), pk);
            let pk2 = ConsensusPublicKey::from_bytes(scheme, &pk.to_bytes()).unwrap();
            assert_eq!(pk2, pk);
        }
    }
}
