[package]
name = "crypto"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
ed25519-dalek = { version = "2", features = ["batch", "rand_core"] }
blake3 = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
